import type { RequestContext } from './types';
import { hashPassword, normalizeEmail, randomId, sha256, clearSessionCookie, validSameOrigin, verifyPassword } from './security';
import { layout, time } from './views';

const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const html=(body:string,status=200,headers:HeadersInit={})=>new Response(body,{status,headers:{'Content-Type':'text/html; charset=utf-8',...headers}});
const redirect=(to:string,headers:HeadersInit={})=>new Response(null,{status:303,headers:{Location:to,...headers}});
const data=async(r:Request)=>Object.fromEntries((await r.formData()).entries()) as Record<string,string>;
function requireUser(c:RequestContext){return c.user?null:redirect('/login?return=/account');}

export async function accountPage(c:RequestContext){const no=requireUser(c);if(no)return no;const u=await c.env.DB.prepare('SELECT email_norm,username,created_at FROM users WHERE id=?').bind(c.user!.id).first<any>();const comments=await c.env.DB.prepare(`SELECT c.id,c.content,c.created_at,i.slug,i.title FROM comments c JOIN investigations i ON i.id=c.investigation_id WHERE c.author_user_id=? ORDER BY c.created_at DESC LIMIT 100`).bind(c.user!.id).all<any>();return html(layout('Account',`<div class="eyebrow">ACCOUNT</div><h1>${esc(u.username)}</h1><div class="dashboard-grid"><div class="side"><a href="#profile">PROFILE</a><a href="#comments">MY COMMENTS</a><a href="#password">PASSWORD</a><a href="#deactivate">DEACTIVATE</a></div><div><section id="profile"><h2>Profile</h2><div class="entry"><b>Email</b><br>${esc(u.email_norm)}<div class="meta">Member since ${time(u.created_at)}</div></div></section><section id="comments"><h2>My Comments</h2>${comments.results.map(x=>`<article class="entry"><a class="blue" href="/investigations/${encodeURIComponent(x.slug)}#comment-${esc(x.id)}">${esc(x.title)}</a><div class="content">${esc(x.content)}</div><div class="meta">${time(x.created_at)}</div></article>`).join('')||'<div class="empty">No comments yet.</div>'}</section><section id="password"><h2>Change password</h2><form class="panel" method="post" action="/api/account/password"><div class="field"><label>CURRENT PASSWORD</label><input type="password" name="current" required></div><div class="field"><label>NEW PASSWORD</label><input type="password" name="next" minlength="4" maxlength="256" required></div><button class="blue">CHANGE PASSWORD</button></form></section><section id="deactivate"><h2>Deactivate account</h2><div class="notice">Deactivation ends your sessions and prevents future login. Your historical public contributions remain part of the public record.</div><form method="post" action="/api/account/deactivate"><label><input type="checkbox" name="confirm" value="yes" required> I understand my published contributions remain.</label><br><br><button>DEACTIVATE ACCOUNT</button></form></section></div></div>`,c.user));}

export async function changePassword(c:RequestContext){const no=requireUser(c);if(no)return no;if(!validSameOrigin(c.request,c.env))return new Response('Invalid origin',{status:403});const d=await data(c.request),next=d.next||'';if(next.length<4||next.length>256)return new Response('Invalid password',{status:400});const cr=await c.env.DB.prepare('SELECT password_hash,password_salt FROM user_credentials WHERE user_id=?').bind(c.user!.id).first<any>();if(!cr||!await verifyPassword(d.current||'',cr.password_salt,cr.password_hash))return new Response('Current password is incorrect',{status:401});const hp=await hashPassword(next),now=Date.now();await c.env.DB.batch([c.env.DB.prepare('UPDATE user_credentials SET password_hash=?,password_salt=?,kdf=?,kdf_params=?,updated_at=? WHERE user_id=?').bind(hp.hash,hp.salt,'PBKDF2-SHA256',hp.params,now,c.user!.id),c.env.DB.prepare('UPDATE sessions SET revoked_at=? WHERE user_id=?').bind(now,c.user!.id),c.env.DB.prepare('INSERT INTO audit_events(id,actor_user_id,event_type,object_type,object_id,created_at) VALUES(?,?,?,?,?,?)').bind(randomId(),c.user!.id,'PASSWORD_CHANGED','USER',c.user!.id,now)]);return redirect('/login?password=changed',{'Set-Cookie':clearSessionCookie()});}

export async function deactivate(c:RequestContext){const no=requireUser(c);if(no)return no;if(!validSameOrigin(c.request,c.env))return new Response('Invalid origin',{status:403});const d=await data(c.request);if(d.confirm!=='yes')return new Response('Confirmation required',{status:400});const now=Date.now();await c.env.DB.batch([c.env.DB.prepare(`UPDATE users SET status='DEACTIVATED',deactivated_at=? WHERE id=?`).bind(now,c.user!.id),c.env.DB.prepare('UPDATE sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL').bind(now,c.user!.id),c.env.DB.prepare('INSERT INTO audit_events(id,actor_user_id,event_type,object_type,object_id,created_at) VALUES(?,?,?,?,?,?)').bind(randomId(),c.user!.id,'ACCOUNT_DEACTIVATED','USER',c.user!.id,now)]);return redirect('/',{'Set-Cookie':clearSessionCookie()});}
