import type { IntelDatabase,DbStatement } from './db/types';
export type AdminInvestigation={id:string;title:string;status:string;updated_at:number};
export class AdminPublishingRepository{
 constructor(private db:IntelDatabase){}
 list(limit=50){return this.db.execute<AdminInvestigation>('SELECT id,title,status,updated_at FROM investigations ORDER BY updated_at DESC,id DESC LIMIT ?',[limit]);}
 investigation(id:string){return this.db.first<{id:string;slug:string;title:string}>('SELECT id,slug,title FROM investigations WHERE id=? LIMIT 1',[id]);}
 create(v:{id:string;slug:string;title:string;summary:string;status:string;author:string;now:number;auditId:string}){const q:DbStatement[]=[{sql:'INSERT INTO investigations(id,slug,title,summary,status,author_user_id,created_at,updated_at,published_at) VALUES(?,?,?,?,?,?,?,?,?)',args:[v.id,v.slug,v.title,v.summary,v.status,v.author,v.now,v.now,v.now]},{sql:'INSERT INTO audit_events(id,actor_user_id,event_type,object_type,object_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)',args:[v.auditId,v.author,'INVESTIGATION_CREATED','INVESTIGATION',v.id,null,v.now]}];return this.db.batch(q);}
 publish(v:{id:string;investigationId:string;type:string;title:string|null;content:string;author:string;now:number;auditId:string}){const q:DbStatement[]=[{sql:'INSERT INTO investigation_updates(id,investigation_id,type,title,content,author_user_id,created_at,published_at) VALUES(?,?,?,?,?,?,?,?)',args:[v.id,v.investigationId,v.type,v.title,v.content,v.author,v.now,v.now]},{sql:'UPDATE investigations SET update_count=update_count+1,updated_at=? WHERE id=?',args:[v.now,v.investigationId]},{sql:'INSERT INTO audit_events(id,actor_user_id,event_type,object_type,object_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)',args:[v.auditId,v.author,'INVESTIGATION_UPDATE_PUBLISHED','UPDATE',v.id,JSON.stringify({investigationId:v.investigationId,type:v.type}),v.now]}];return this.db.batch(q);}
}
