import type { DbStatement, IntelDatabase } from './db/types';
export class CommunityRepository{
constructor(private db:IntelDatabase){}
followState(user:string,investigation:string){return this.db.first<{x:number}>('SELECT 1 x FROM investigation_follows WHERE user_id=? AND investigation_id=? LIMIT 1',[user,investigation]);}
followerRole(user:string,investigation:string){return this.db.first<{role:string|null}>(`SELECT im.role FROM investigation_follows f LEFT JOIN investigation_members im ON im.investigation_id=f.investigation_id AND im.user_id=f.user_id WHERE f.user_id=? AND f.investigation_id=? LIMIT 1`,[user,investigation]);}
follow(user:string,investigation:string,now:number){return this.db.batch([{sql:'INSERT OR IGNORE INTO investigation_follows(user_id,investigation_id,created_at) VALUES(?,?,?)',args:[user,investigation,now]},{sql:'UPDATE investigations SET follower_count=follower_count+CASE WHEN changes()>0 THEN 1 ELSE 0 END WHERE id=?',args:[investigation]}]);}
unfollow(user:string,investigation:string){return this.db.batch([{sql:'DELETE FROM investigation_follows WHERE user_id=? AND investigation_id=?',args:[user,investigation]},{sql:'UPDATE investigations SET follower_count=max(0,follower_count-CASE WHEN changes()>0 THEN 1 ELSE 0 END) WHERE id=?',args:[investigation]}]);}
createInvestigation(v:{id:string;slug:string;title:string;summary:string;actor:string;now:number;auditId:string;tagMode?:string;tags?:string[]}){return this.db.batch([{sql:'INSERT INTO investigations(id,slug,title,summary,status,author_user_id,created_at,updated_at,published_at,follower_count,comment_tag_mode) VALUES(?,?,?,?,?,?,?,?,?,1,?)',args:[v.id,v.slug,v.title,v.summary,'ACTIVE',v.actor,v.now,v.now,v.now,v.tagMode==='COMMUNITY'?'COMMUNITY':'CREATOR_ONLY']},{sql:'INSERT INTO investigation_follows(user_id,investigation_id,created_at) VALUES(?,?,?)',args:[v.actor,v.id,v.now]},{sql:"INSERT INTO investigation_members(investigation_id,user_id,role,created_at,granted_by) VALUES(?,?,'OWNER',?,?)",args:[v.id,v.actor,v.now,v.actor]},{sql:'INSERT INTO audit_events(id,actor_user_id,event_type,object_type,object_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)',args:[v.auditId,v.actor,'INVESTIGATION_CREATED','INVESTIGATION',v.id,'{}',v.now]}]);}
parent(id:string){return this.db.first<any>('SELECT c.id,c.root_id,c.depth,c.investigation_id,c.author_user_id FROM comments c WHERE c.id=?',[id]);}
investigationSlug(id:string){return this.db.first<{slug:string}>('SELECT slug FROM investigations WHERE id=? AND published_at IS NOT NULL LIMIT 1',[id]);}
role(user:string,investigation:string){return this.db.first<{role:'OWNER'|'MODERATOR'}>('SELECT role FROM investigation_members WHERE investigation_id=? AND user_id=? LIMIT 1',[investigation,user]);}
followers(investigation:string){return this.db.execute<{id:string;username:string;role:string|null}>(`SELECT u.id,u.username,im.role FROM investigation_follows f JOIN users u ON u.id=f.user_id LEFT JOIN investigation_members im ON im.investigation_id=f.investigation_id AND im.user_id=f.user_id WHERE f.investigation_id=? AND u.status='ACTIVE' ORDER BY CASE im.role WHEN 'OWNER' THEN 0 WHEN 'MODERATOR' THEN 1 ELSE 2 END,u.username LIMIT 250`,[investigation]);}
setModerator(v:{investigation:string;actor:string;target:string;enabled:boolean;now:number;auditId:string}){const statements:DbStatement[]=[];if(v.enabled)statements.push({sql:`INSERT INTO investigation_members(investigation_id,user_id,role,created_at,granted_by) SELECT ?,?,'MODERATOR',?,? WHERE ?<>? AND EXISTS(SELECT 1 FROM investigation_members WHERE investigation_id=? AND user_id=? AND role='OWNER') AND EXISTS(SELECT 1 FROM investigation_follows WHERE investigation_id=? AND user_id=?) ON CONFLICT(investigation_id,user_id) DO UPDATE SET role=CASE WHEN investigation_members.role='OWNER' THEN 'OWNER' ELSE 'MODERATOR' END,granted_by=excluded.granted_by`,args:[v.investigation,v.target,v.now,v.actor,v.actor,v.target,v.investigation,v.actor,v.investigation,v.target]});else statements.push({sql:`DELETE FROM investigation_members WHERE investigation_id=? AND user_id=? AND role='MODERATOR' AND EXISTS(SELECT 1 FROM investigation_members owner WHERE owner.investigation_id=? AND owner.user_id=? AND owner.role='OWNER')`,args:[v.investigation,v.target,v.investigation,v.actor]});statements.push({sql:'INSERT OR IGNORE INTO notifications(id,user_id,type,investigation_id,payload_json,created_at) VALUES(?,?,?,?,?,?)',args:[v.auditId+'-notice',v.target,v.enabled?'MODERATOR_GRANTED':'MODERATOR_REVOKED',v.investigation,JSON.stringify({actorUserId:v.actor}),v.now]},{sql:'INSERT INTO audit_events(id,actor_user_id,event_type,object_type,object_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)',args:[v.auditId,v.actor,v.enabled?'INVESTIGATION_MODERATOR_GRANTED':'INVESTIGATION_MODERATOR_REVOKED','INVESTIGATION',v.investigation,JSON.stringify({userId:v.target}),v.now]});return this.db.batch(statements);}
async publishComment(v:{id:string;investigation:string;parent?:string|null;parentAuthor?:string|null;root?:string|null;depth:number;actor:string;description:string;content:string;tagId?:string|null;now:number;auditId:string;notificationId:string}){const core:DbStatement[]=[{sql:'INSERT INTO comments(id,investigation_id,parent_id,root_id,depth,author_user_id,description,content,tag_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',args:[v.id,v.investigation,v.parent??null,v.root??null,v.depth,v.actor,v.description,v.content,v.tagId??null,v.now]},{sql:'UPDATE investigations SET comment_count=comment_count+1,updated_at=? WHERE id=?',args:[v.now,v.investigation]}];if(v.parent)core.push({sql:'UPDATE comments SET reply_count=reply_count+1 WHERE id=?',args:[v.parent]});core.push({sql:'INSERT INTO audit_events(id,actor_user_id,event_type,object_type,object_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)',args:[v.auditId,v.actor,'COMMENT_PUBLISHED','COMMENT',v.id,JSON.stringify({investigationId:v.investigation,parentId:v.parent??null}),v.now]});const result=await this.db.batch(core);try{const notices:DbStatement[]=[];if(v.parentAuthor&&v.parentAuthor!==v.actor)notices.push({sql:'INSERT OR IGNORE INTO notifications(id,user_id,type,investigation_id,comment_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)',args:[v.notificationId+'-reply',v.parentAuthor,'COMMENT_REPLY',v.investigation,v.id,JSON.stringify({actorUserId:v.actor,parentId:v.parent}),v.now]});notices.push({sql:"INSERT OR IGNORE INTO notifications(id,user_id,type,investigation_id,comment_id,payload_json,created_at) SELECT ?||'-'||im.user_id,im.user_id,'INVESTIGATION_COMMENT',im.investigation_id,?,?,? FROM investigation_members im WHERE im.investigation_id=? AND im.role IN ('OWNER','MODERATOR') AND im.user_id<>?",args:[v.notificationId,v.id,JSON.stringify({actorUserId:v.actor}),v.now,v.investigation,v.actor]});if(notices.length)await this.db.batch(notices);}catch(error){console.error('comment notifications unavailable after successful publish',error);}return result;}
async commentForEdit(id:string){try{return await this.db.first<any>('SELECT id,investigation_id,parent_id,author_user_id,description,content,visibility_status FROM comments WHERE id=? LIMIT 1',[id]);}catch(error){console.error('enhanced edit read unavailable; using compatibility read',error);return this.db.first<any>("SELECT id,investigation_id,parent_id,author_user_id,'' description,content,visibility_status FROM comments WHERE id=? LIMIT 1",[id]);}}
commentEditHistory(id:string){return this.db.execute<any>("SELECT created_at edited_at FROM audit_events WHERE event_type='COMMENT_EDITED' AND object_type='COMMENT' AND object_id=? ORDER BY created_at ASC,id ASC",[id]);}
editComment(v:{id:string;actor:string;description:string;content:string;previousDescription:string;previousContent:string;now:number;auditId:string}){return this.db.batch([{sql:'UPDATE comments SET description=?,content=? WHERE id=? AND author_user_id=?',args:[v.description,v.content,v.id,v.actor]},{sql:'INSERT INTO audit_events(id,actor_user_id,event_type,object_type,object_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)',args:[v.auditId,v.actor,'COMMENT_EDITED','COMMENT',v.id,JSON.stringify({previousDescription:v.previousDescription,previousContent:v.previousContent}),v.now]}]);}
commentForModeration(id:string){return this.db.first<{id:string;investigation_id:string;visibility_status:string;like_count:number}>('SELECT id,investigation_id,visibility_status,like_count FROM comments WHERE id=? LIMIT 1',[id]);}
moderateComment(v:{comment:string;investigation:string;actor:string;remove:boolean;reason:string;now:number;actionId:string;auditId:string}){const visibility=v.remove?'MOD_REMOVED':'VISIBLE';return this.db.batch([{sql:'UPDATE comments SET visibility_status=?,moderation_reason=?,moderated_at=? WHERE id=? AND investigation_id=?',args:[visibility,v.reason,v.now,v.comment,v.investigation]},{sql:"UPDATE comment_reports SET status='RESOLVED' WHERE comment_id=? AND status='OPEN'",args:[v.comment]},{sql:"UPDATE moderation_queue SET status=?,resolved_at=?,resolved_by=? WHERE comment_id=? AND status='PENDING'",args:[v.remove?'CONFIRMED':'RESTORED',v.now,v.actor,v.comment]},{sql:'INSERT INTO moderation_actions(id,comment_id,moderator_user_id,action,reason,created_at) VALUES(?,?,?,?,?,?)',args:[v.actionId,v.comment,v.actor,v.remove?'REMOVE':'RESTORE',v.reason,v.now]},{sql:`INSERT OR IGNORE INTO notifications(id,user_id,type,investigation_id,comment_id,payload_json,created_at) SELECT ?||'-author',author_user_id,?,investigation_id,id,?,? FROM comments WHERE id=? AND author_user_id<>?`,args:[v.actionId,v.remove?'COMMENT_REMOVED':'COMMENT_RESTORED',JSON.stringify({actorUserId:v.actor,reason:v.reason}),v.now,v.comment,v.actor]},{sql:'INSERT INTO audit_events(id,actor_user_id,event_type,object_type,object_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)',args:[v.auditId,v.actor,v.remove?'COMMENT_REMOVE':'COMMENT_RESTORE','COMMENT',v.comment,JSON.stringify({investigationId:v.investigation,reason:v.reason}),v.now]}]);}
async tagMode(investigation:string){try{return await this.db.first<{comment_tag_mode:string}>('SELECT comment_tag_mode FROM investigations WHERE id=? LIMIT 1',[investigation]);}catch(error){console.error('comment tag mode unavailable during schema rollout',error);return null;}}
async commentTags(investigation:string){try{return await this.db.execute<{id:string;name:string}>(`SELECT t.id,t.name FROM investigation_comment_tags ict JOIN tags t ON t.id=ict.tag_id WHERE ict.investigation_id=? ORDER BY t.name LIMIT 40`,[investigation]);}catch(error){console.error('comment tags unavailable during schema rollout',error);return {rows:[]};}}
tagForInvestigation(investigation:string,tag:string){return this.db.first<{id:string}>(`SELECT t.id FROM investigation_comment_tags ict JOIN tags t ON t.id=ict.tag_id WHERE ict.investigation_id=? AND t.id=? LIMIT 1`,[investigation,tag]);}
createCommentTag(v:{id:string;investigation:string;name:string;normalized:string;actor:string;now:number}){return this.db.batch([{sql:'INSERT OR IGNORE INTO tags(id,name,normalized_name) VALUES(?,?,?)',args:[v.id,v.name,v.normalized]},{sql:'INSERT OR IGNORE INTO investigation_comment_tags(investigation_id,tag_id,created_by,created_at) SELECT ?,id,?,? FROM tags WHERE normalized_name=?',args:[v.investigation,v.actor,v.now,v.normalized]}]);}
likeState(user:string,comment:string){return this.db.first<{x:number}>('SELECT 1 x FROM comment_likes WHERE user_id=? AND comment_id=? LIMIT 1',[user,comment]);}
like(user:string,comment:string,now:number){return this.db.batch([{sql:'INSERT OR IGNORE INTO comment_likes(user_id,comment_id,created_at) VALUES(?,?,?)',args:[user,comment,now]},{sql:'UPDATE comments SET like_count=like_count+CASE WHEN changes()>0 THEN 1 ELSE 0 END WHERE id=?',args:[comment]}]);}
unlike(user:string,comment:string){return this.db.batch([{sql:'DELETE FROM comment_likes WHERE user_id=? AND comment_id=?',args:[user,comment]},{sql:'UPDATE comments SET like_count=max(0,like_count-CASE WHEN changes()>0 THEN 1 ELSE 0 END) WHERE id=?',args:[comment]}]);}
notifyMentions(v:{usernames:string[];actor:string;investigation:string;comment:string;now:number;notificationPrefix:string}){const names=[...new Set(v.usernames.map(x=>x.toLowerCase()))].slice(0,5);if(!names.length)return Promise.resolve();const placeholders=names.map(()=>'?').join(',');return this.db.execute(`INSERT OR IGNORE INTO notifications(id,user_id,type,investigation_id,comment_id,payload_json,created_at) SELECT ?||'-'||id,id,'MENTION',?,?,?,? FROM users WHERE username_norm IN (${placeholders}) AND id<>? AND status='ACTIVE'`,[v.notificationPrefix,v.investigation,v.comment,JSON.stringify({actorUserId:v.actor}),v.now,...names,v.actor]);}
userByUsername(username:string){return this.db.first<{id:string;username:string}>("SELECT id,username FROM users WHERE username_norm=? AND status='ACTIVE' LIMIT 1",[username.toLowerCase()]);}
userFollowState(actor:string,target:string){return this.db.first<{x:number}>('SELECT 1 x FROM user_follows WHERE follower_user_id=? AND followed_user_id=? LIMIT 1',[actor,target]);}
followUser(actor:string,target:string,now:number,notificationId:string){return this.db.batch([{sql:'INSERT OR IGNORE INTO user_follows(follower_user_id,followed_user_id,created_at) VALUES(?,?,?)',args:[actor,target,now]},{sql:"INSERT OR IGNORE INTO notifications(id,user_id,type,payload_json,created_at) VALUES(?,?,'USER_FOLLOWED',?,?)",args:[notificationId,target,JSON.stringify({actorUserId:actor}),now]}]);}
unfollowUser(actor:string,target:string){return this.db.execute('DELETE FROM user_follows WHERE follower_user_id=? AND followed_user_id=?',[actor,target]);}
saveState(user:string,type:string,id:string){return this.db.first<{x:number}>('SELECT 1 x FROM saved_objects WHERE user_id=? AND object_type=? AND object_id=? LIMIT 1',[user,type,id]);}
save(user:string,type:string,id:string,now:number){return this.db.execute('INSERT OR IGNORE INTO saved_objects(user_id,object_type,object_id,created_at) VALUES(?,?,?,?)',[user,type,id,now]);}
unsave(user:string,type:string,id:string){return this.db.execute('DELETE FROM saved_objects WHERE user_id=? AND object_type=? AND object_id=?',[user,type,id]);}
}

