import type { DbStatement, IntelDatabase } from './db/types';
export type RelationshipInput={id:string;subject:string;predicate:string;object:string;source?:string|null;evidence?:string|null;actor:string;now:number;confidence?:number;verificationState?:string;observedAt?:number|null;validFrom?:number|null;validTo?:number|null;assertionNote?:string|null};
export class EntityRepository{
constructor(private db:IntelDatabase){}
get(id:string){return this.db.first<any>('SELECT id,type,canonical_name,description,created_at,updated_at FROM entities WHERE id=?',[id]);}
relationships(id:string,limit=50){return this.db.execute<any>(`SELECT r.id,r.subject_entity_id,r.predicate,r.object_entity_id,r.valid_from,r.valid_to,r.observed_at,r.confidence,r.verification_state,r.assertion_note,r.created_at,a.canonical_name subject_name,b.canonical_name object_name,(SELECT COUNT(*) FROM relationship_sources rs WHERE rs.relationship_id=r.id) source_count,(SELECT COUNT(*) FROM relationship_evidence re WHERE re.relationship_id=r.id) evidence_count FROM entity_relationships r JOIN entities a ON a.id=r.subject_entity_id JOIN entities b ON b.id=r.object_entity_id WHERE r.subject_entity_id=? OR r.object_entity_id=? ORDER BY COALESCE(r.valid_from,r.observed_at,r.created_at) DESC,r.id DESC LIMIT ?`,[id,id,limit]);}
create(v:{id:string;type:string;name:string;normalized:string;description:string;now:number;investigationId?:string;role?:string|null}){const q:DbStatement[]=[{sql:'INSERT INTO entities(id,type,canonical_name,normalized_name,description,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',args:[v.id,v.type,v.name,v.normalized,v.description,v.now,v.now]}];if(v.investigationId)q.push({sql:'INSERT OR IGNORE INTO investigation_entities(investigation_id,entity_id,role) VALUES(?,?,?)',args:[v.investigationId,v.id,v.role??null]});return this.db.batch(q);}
relationship(v:RelationshipInput){const confidence=Math.max(0,Math.min(1,v.confidence??0.5));const verification=v.verificationState??'UNVERIFIED';const q:DbStatement[]=[{sql:'INSERT INTO entity_relationships(id,subject_entity_id,predicate,object_entity_id,source_id,evidence_id,valid_from,valid_to,created_by,created_at,confidence,verification_state,observed_at,assertion_note) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',args:[v.id,v.subject,v.predicate,v.object,v.source??null,v.evidence??null,v.validFrom??null,v.validTo??null,v.actor,v.now,confidence,verification,v.observedAt??v.now,v.assertionNote??null]}];if(v.source)q.push({sql:"INSERT INTO relationship_sources(relationship_id,source_id,support_type,assertion_note,created_by,created_at) VALUES(?,?,'SUPPORTS',?,?,?)",args:[v.id,v.source,v.assertionNote??null,v.actor,v.now]});if(v.evidence)q.push({sql:"INSERT INTO relationship_evidence(relationship_id,evidence_id,support_type,assertion_note,created_by,created_at) VALUES(?,?,'SUPPORTS',?,?,?)",args:[v.id,v.evidence,v.assertionNote??null,v.actor,v.now]});return this.db.batch(q);}
resolutionCandidates(normalized:string,type:string,excludeId?:string,limit=10){return this.db.execute<any>(`SELECT id,type,canonical_name,normalized_name,CASE WHEN normalized_name=? THEN 1.0 WHEN type=? AND normalized_name LIKE ? THEN 0.75 ELSE 0.5 END score FROM entities WHERE (? IS NULL OR id<>?) AND (normalized_name=? OR (type=? AND normalized_name LIKE ?)) ORDER BY score DESC,canonical_name,id LIMIT ?`,[normalized,type,`${normalized}%`,excludeId??null,excludeId??null,normalized,type,`${normalized}%`,Math.min(25,Math.max(1,limit))]);}
}
