import type { RequestContext } from './types';
import { randomId, validSameOrigin } from './security';
import { layout } from './views';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const html=(b:string,s=200)=>new Response(b,{status:s,headers:{'Content-Type':'text/html; charset=utf-8'}});
const redirect=(to:string)=>new Response(null,{status:303,headers:{Location:to}});
const fd=async(r:Request)=>Object.fromEntries((await r.formData()).entries()) as Record<string,string>;
const TYPES=['PERSON','ORGANIZATION','BUSINESS','GOVERNMENT_BODY','PROPERTY','PARCEL','CONTRACT','DOCUMENT','PROJECT'];
function admin(c:RequestContext){return c.user?.isAdmin;}
export async function entityPage(c:RequestContext,id:string){const e=await c.env.DB.prepare('SELECT * FROM entities WHERE id=?').bind(id).first<any>();if(!e)return html(layout('Not found','<h1>Entity not found</h1>',c.user),404);const rel=await c.env.DB.prepare(`SELECT r.*,a.canonical_name from_name,b.canonical_name to_name FROM entity_relationships r JOIN entities a ON a.id=r.from_entity_id JOIN entities b ON b.id=r.to_entity_id WHERE r.from_entity_id=? OR r.to_entity_id=? ORDER BY r.created_at DESC LIMIT 100`).bind(id,id).all<any>();return html(layout(e.canonical_name,`<div class="eyebrow">${esc(e.type.replaceAll('_',' '))}</div><h1>${esc(e.canonical_name)}</h1><p class="lede">${esc(e.description||'')}</p><h2>Documented relationships</h2>${rel.results.map(r=>`<article class="entry"><a class="blue" href="/entities/${esc(r.from_entity_id)}">${esc(r.from_name)}</a> <b>${esc(r.relationship_type.replaceAll('_',' '))}</b> <a class="blue" href="/entities/${esc(r.to_entity_id)}">${esc(r.to_name)}</a>${r.source_id?'<div class="meta">Sourced relationship</div>':'<div class="meta">Source pending</div>'}</article>`).join('')||'<div class="empty">No relationships published.</div>'}`,c.user,`INTEL entity record for ${e.canonical_name}.`,`${c.env.APP_ORIGIN}/entities/${encodeURIComponent(id)}`));}
export async function createEntity(c:RequestContext){if(!admin(c))return new Response('Forbidden',{status:403});if(!validSameOrigin(c.request,c.env))return new Response('Invalid origin',{status:403});const d=await fd(c.request),type=d.type,name=(d.name||'').trim();if(!TYPES.includes(type)||!name)return new Response('Invalid entity',{status:400});const id=randomId(),now=Date.now();await c.env.DB.prepare('INSERT INTO entities(id,type,canonical_name,description,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(id,type,name,(d.description||'').trim(),now,now).run();if(d.investigation_id)await c.env.DB.prepare('INSERT OR IGNORE INTO investigation_entities(investigation_id,entity_id,created_at) VALUES(?,?,?)').bind(d.investigation_id,id,now).run();return redirect(`/entities/${id}`);}
export async function createRelationship(c:RequestContext){if(!admin(c))return new Response('Forbidden',{status:403});if(!validSameOrigin(c.request,c.env))return new Response('Invalid origin',{status:403});const d=await fd(c.request);if(!d.from_entity_id||!d.to_entity_id||!d.relationship_type)return new Response('Invalid relationship',{status:400});const id=randomId();await c.env.DB.prepare('INSERT INTO entity_relationships(id,from_entity_id,to_entity_id,relationship_type,source_id,notes,created_by,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,d.from_entity_id,d.to_entity_id,d.relationship_type.trim().toUpperCase().replace(/\s+/g,'_'),d.source_id||null,(d.notes||'').trim(),c.user!.id,Date.now()).run();return redirect(`/entities/${d.from_entity_id}`);}
