import type { DbStatement, IntelDatabase } from './db/types';
export type RelationshipInput={id:string;subject:string;predicate:string;object:string;source?:string|null;evidence?:string|null;actor:string;now:number;confidence?:number;verificationState?:string;observedAt?:number|null;validFrom?:number|null;validTo?:number|null;assertionNote?:string|null};
export type ResolutionCandidate={id:string;type:string;canonical_name:string;normalized_name:string;matched_on:'CANONICAL'|'ALIAS';match_value:string;score:number;reason:string};
export class EntityRepository{
constructor(private db:IntelDatabase){}
get(id:string){return this.db.first<any>('SELECT id,type,canonical_name,description,created_at,updated_at FROM entities WHERE id=?',[id]);}
relationships(id:string,limit=50){return this.db.execute<any>(`SELECT r.id,r.subject_entity_id,r.predicate,r.object_entity_id,r.source_id,r.evidence_id,r.valid_from,r.valid_to,r.observed_at,r.confidence,r.verification_state,r.assertion_note,r.created_at,a.canonical_name subject_name,b.canonical_name object_name,coalesce(rs.source_count,0) source_count,coalesce(re.evidence_count,0) evidence_count FROM entity_relationships r JOIN entities a ON a.id=r.subject_entity_id JOIN entities b ON b.id=r.object_entity_id LEFT JOIN (SELECT relationship_id,count(*) source_count FROM relationship_sources WHERE relationship_id IN (SELECT id FROM entity_relationships WHERE subject_entity_id=? OR object_entity_id=?) GROUP BY relationship_id) rs ON rs.relationship_id=r.id LEFT JOIN (SELECT relationship_id,count(*) evidence_count FROM relationship_evidence WHERE relationship_id IN (SELECT id FROM entity_relationships WHERE subject_entity_id=? OR object_entity_id=?) GROUP BY relationship_id) re ON re.relationship_id=r.id WHERE r.subject_entity_id=? OR r.object_entity_id=? ORDER BY COALESCE(r.valid_from,r.observed_at,r.created_at) DESC,r.id DESC LIMIT ?`,[id,id,id,id,id,id,Math.min(100,Math.max(1,limit))]);}
create(v:{id:string;type:string;name:string;normalized:string;description:string;now:number;investigationId?:string;role?:string|null}){const q:DbStatement[]=[{sql:'INSERT INTO entities(id,type,canonical_name,normalized_name,description,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',args:[v.id,v.type,v.name,v.normalized,v.description,v.now,v.now]}];if(v.investigationId)q.push({sql:'INSERT OR IGNORE INTO investigation_entities(investigation_id,entity_id,role) VALUES(?,?,?)',args:[v.investigationId,v.id,v.role??null]});return this.db.batch(q);}
relationship(v:RelationshipInput){const confidence=Math.max(0,Math.min(1,v.confidence??0.5));const verification=v.verificationState??'UNVERIFIED';const q:DbStatement[]=[{sql:'INSERT INTO entity_relationships(id,subject_entity_id,predicate,object_entity_id,source_id,evidence_id,valid_from,valid_to,created_by,created_at,confidence,verification_state,observed_at,assertion_note) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',args:[v.id,v.subject,v.predicate,v.object,v.source??null,v.evidence??null,v.validFrom??null,v.validTo??null,v.actor,v.now,confidence,verification,v.observedAt??v.now,v.assertionNote??null]}];if(v.source)q.push({sql:"INSERT INTO relationship_sources(relationship_id,source_id,support_type,assertion_note,created_by,created_at) VALUES(?,?,'SUPPORTS',?,?,?)",args:[v.id,v.source,v.assertionNote??null,v.actor,v.now]});if(v.evidence)q.push({sql:"INSERT INTO relationship_evidence(relationship_id,evidence_id,support_type,assertion_note,created_by,created_at) VALUES(?,?,'SUPPORTS',?,?,?)",args:[v.id,v.evidence,v.assertionNote??null,v.actor,v.now]});return this.db.batch(q);}
async resolutionCandidates(normalized:string,type:string,excludeId?:string,limit=10):Promise<{rows:ResolutionCandidate[]}>{const safeLimit=Math.min(25,Math.max(1,limit)),prefix=`${normalized}%`;const result=await this.db.execute<ResolutionCandidate>(`SELECT id,type,canonical_name,normalized_name,matched_on,match_value,score,reason FROM (SELECT e.id,e.type,e.canonical_name,e.normalized_name,'CANONICAL' matched_on,e.normalized_name match_value,CASE WHEN e.normalized_name=? THEN 1.0 ELSE 0.78 END score,CASE WHEN e.normalized_name=? THEN 'exact canonical name' ELSE 'canonical prefix' END reason FROM entities e WHERE e.type=? AND (? IS NULL OR e.id<>?) AND (e.normalized_name=? OR e.normalized_name LIKE ?) UNION ALL SELECT e.id,e.type,e.canonical_name,e.normalized_name,'ALIAS' matched_on,a.normalized_alias match_value,CASE WHEN a.normalized_alias=? THEN 0.96 ELSE 0.74 END score,CASE WHEN a.normalized_alias=? THEN 'exact alias' ELSE 'alias prefix' END reason FROM entity_aliases a JOIN entities e ON e.id=a.entity_id WHERE e.type=? AND (? IS NULL OR e.id<>?) AND (a.normalized_alias=? OR a.normalized_alias LIKE ?)) ORDER BY score DESC,canonical_name,id LIMIT ?`,[normalized,normalized,type,excludeId??null,excludeId??null,normalized,prefix,normalized,normalized,type,excludeId??null,excludeId??null,normalized,prefix,safeLimit]);const best=new Map<string,ResolutionCandidate>();for(const row of result.rows){const prior=best.get(row.id);if(!prior||Number(row.score)>Number(prior.score))best.set(row.id,row);}return{rows:[...best.values()].slice(0,safeLimit)};}
}
