import core from './index';
import type { Env,RequestContext } from './types';
import { currentUser,withSecurity,validSameOrigin } from './security';
import { accountPage,changePassword,deactivate } from './account';
import { entityPage,createEntity,createRelationship } from './entities';
import { moderationPage,moderate } from './moderation';
import { uploadEvidence } from './adminEvidence';
import { evidencePage,robots,sitemap } from './publicRecords';
import { publishCorrection } from './corrections';
import { markNotificationsRead,notifyFollowers,notify } from './notifications';
import { likeUpdate,portableExport } from './interactions';
import { layout } from './views';
const html=(b:string,s=200)=>new Response(b,{status:s,headers:{'Content-Type':'text/html; charset=utf-8'}});
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
async function tools(c:RequestContext){if(!c.user?.isAdmin)return new Response('Forbidden',{status:403});const inv=await c.env.DB.prepare('SELECT id,title FROM investigations ORDER BY updated_at DESC LIMIT 100').all<any>(),ents=await c.env.DB.prepare('SELECT id,canonical_name FROM entities ORDER BY updated_at DESC LIMIT 200').all<any>();return html(layout('Admin tools',`<div class="eyebrow">ADMIN</div><h1>INTELLIGENCE TOOLS</h1><p><a class="blue" href="/admin">PUBLISH UPDATES</a> · <a class="blue" href="/admin/moderation">MODERATION</a> · <a class="blue" href="/admin/export">EXPORT DATA</a></p><h2>Evidence</h2><form class="panel" method="post" enctype="multipart/form-data" action="/api/admin/evidence"><div class="field"><label>INVESTIGATION</label><select name="investigation_id">${inv.results.map(i=>`<option value="${esc(i.id)}">${esc(i.title)}</option>`).join('')}</select></div><div class="field"><label>TITLE</label><input name="title" required></div><div class="field"><label>DESCRIPTION</label><textarea name="description"></textarea></div><div class="field"><label>CLASSIFICATION</label><select name="verification_state">${['PRIMARY_SOURCE','PUBLIC_RECORD','VERIFIED','SECONDARY_SOURCE','UNVERIFIED','DISPUTED'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>FILE · MAX 20 MB</label><input type="file" name="file" required></div><button class="blue">PUBLISH EVIDENCE</button></form><h2>Entity</h2><form class="panel" method="post" action="/api/admin/entities"><div class="field"><label>TYPE</label><select name="type">${['PERSON','ORGANIZATION','BUSINESS','GOVERNMENT_BODY','PROPERTY','PARCEL','CONTRACT','DOCUMENT','PROJECT'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>NAME</label><input name="name" required></div><div class="field"><label>DESCRIPTION</label><textarea name="description"></textarea></div><div class="field"><label>INVESTIGATION</label><select name="investigation_id"><option value="">None</option>${inv.results.map(i=>`<option value="${esc(i.id)}">${esc(i.title)}</option>`).join('')}</select></div><button class="blue">CREATE ENTITY</button></form><h2>Relationship</h2><form class="panel" method="post" action="/api/admin/relationships"><div class="field"><label>SUBJECT</label><select name="subject_entity_id">${ents.results.map(e=>`<option value="${esc(e.id)}">${esc(e.canonical_name)}</option>`).join('')}</select></div><div class="field"><label>RELATIONSHIP</label><input name="predicate" placeholder="MEMBER OF" required></div><div class="field"><label>OBJECT</label><select name="object_entity_id">${ents.results.map(e=>`<option value="${esc(e.id)}">${esc(e.canonical_name)}</option>`).join('')}</select></div><button class="blue">PUBLISH RELATIONSHIP</button></form>`,c.user));}
async function route(request:Request,env:Env){const url=new URL(request.url),user=await currentUser(request,env),c:RequestContext={request,env,url,user},p=url.pathname;let m:RegExpMatchArray|null;if(request.method==='POST'&&!validSameOrigin(request,env))return new Response('Invalid origin',{status:403});if(request.method==='GET'&&p==='/account')return accountPage(c);if(request.method==='POST'&&p==='/api/account/password')return changePassword(c);if(request.method==='POST'&&p==='/api/account/deactivate')return deactivate(c);if(request.method==='GET'&&p==='/admin/tools')return tools(c);if(request.method==='GET'&&p==='/admin/export')return portableExport(c);if(request.method==='GET'&&p==='/admin/moderation')return moderationPage(c);if(request.method==='POST'&&(m=p.match(/^\/api\/admin\/moderation\/([^/]+)$/)))return moderate(c,m[1]);if(request.method==='GET'&&(m=p.match(/^\/entities\/([^/]+)$/)))return entityPage(c,m[1]);if(request.method==='POST'&&p==='/api/admin/entities')return createEntity(c);if(request.method==='POST'&&p==='/api/admin/relationships')return createRelationship(c);if(request.method==='POST'&&p==='/api/admin/evidence'){if(!user?.isAdmin)return new Response('Forbidden',{status:403});const clone=request.clone(),fd=await clone.formData();return uploadEvidence(c,String(fd.get('investigation_id')||''));}if(request.method==='GET'&&(m=p.match(/^\/evidence\/([^/]+)$/))&&!p.startsWith('/evidence/files/'))return evidencePage(c,m[1]);if(request.method==='POST'&&(m=p.match(/^\/api\/updates\/([^/]+)\/like$/)))return likeUpdate(c,m[1]);if(request.method==='POST'&&(m=p.match(/^\/api\/admin\/updates\/([^/]+)\/correction$/)))return publishCorrection(c,m[1]);if(request.method==='POST'&&p==='/api/notifications/read')return markNotificationsRead(c);if(request.method==='GET'&&p==='/robots.txt')return robots(c);if(request.method==='GET'&&p==='/sitemap.xml')return sitemap(c);
 const clone=request.method==='POST'?request.clone():null,updateMatch=p.match(/^\/api\/admin\/investigations\/([^/]+)\/updates$/),commentMatch=p.match(/^\/api\/investigations\/([^/]+)\/comments$/);let posted:FormData|null=null;if(clone&&(updateMatch||commentMatch))posted=await clone.formData();const res=await core.fetch(request,env);if(res.status>=300&&res.status<400&&user&&updateMatch){const u=await env.DB.prepare('SELECT id FROM investigation_updates WHERE investigation_id=? ORDER BY published_at DESC LIMIT 1').bind(updateMatch[1]).first<any>();if(u)await notifyFollowers(env,updateMatch[1],u.id,user.id);}if(res.status>=300&&res.status<400&&user&&commentMatch&&posted?.get('parent_id')){const parent=await env.DB.prepare('SELECT author_user_id FROM comments WHERE id=?').bind(String(posted.get('parent_id'))).first<any>(),latest=await env.DB.prepare('SELECT id FROM comments WHERE investigation_id=? AND author_user_id=? ORDER BY created_at DESC LIMIT 1').bind(commentMatch[1],user.id).first<any>();if(parent&&latest&&parent.author_user_id!==user.id)await notify(env,parent.author_user_id,'REPLY',{investigationId:commentMatch[1],commentId:latest.id});}return res;}
export default {async fetch(request:Request,env:Env){try{return withSecurity(await route(request,env));}catch(e){console.error(e);return withSecurity(html('<!doctype html><title>INTEL unavailable</title><h1>INTEL is temporarily unavailable.</h1>',500));}}};
