import type { RequestContext } from './types';
import { randomId, validSameOrigin } from './security';
import { layout, time } from './views';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const html=(b:string,s=200)=>new Response(b,{status:s,headers:{'Content-Type':'text/html; charset=utf-8'}});
const redirect=(to:string)=>new Response(null,{status:303,headers:{Location:to}});
const fd=async(r:Request)=>Object.fromEntries((await r.formData()).entries()) as Record<string,string>;
export async function moderationPage(c:RequestContext){if(!c.user?.isAdmin)return new Response('Forbidden',{status:403});const q=await c.env.DB.prepare(`SELECT q.*,c.content,u.username FROM moderation_queue q JOIN comments c ON c.id=q.comment_id JOIN users u ON u.id=c.author_user_id WHERE q.status='PENDING' ORDER BY q.created_at ASC LIMIT 100`).all<any>();return html(layout('Moderation',`<div class="eyebrow">ADMIN</div><h1>MODERATION</h1>${q.results.map(x=>`<article class="entry"><div class="type">${esc(x.trigger_category)} · ${x.trigger_count} ELIGIBLE REPORTS</div><p><b>${esc(x.username)}</b>: ${esc(x.content)}</p><div class="meta">Auto-hidden ${time(x.created_at)}</div><form method="post" action="/api/admin/moderation/${esc(x.id)}"><input type="hidden" name="comment_id" value="${esc(x.comment_id)}"><button name="action" value="RESTORE" class="blue">RESTORE</button> <button name="action" value="REMOVE">CONFIRM REMOVAL</button><div class="field"><label>MODERATION REASON</label><input name="reason" maxlength="500" required></div></form></article>`).join('')||'<div class="empty">Moderation queue is clear.</div>'}`,c.user));}
export async function moderate(c:RequestContext,queueId:string){if(!c.user?.isAdmin)return new Response('Forbidden',{status:403});if(!validSameOrigin(c.request,c.env))return new Response('Invalid origin',{status:403});const d=await fd(c.request),action=d.action;if(!['RESTORE','REMOVE'].includes(action)||!(d.reason||'').trim())return new Response('Invalid action',{status:400});const q=await c.env.DB.prepare(`SELECT comment_id FROM moderation_queue WHERE id=? AND status='PENDING'`).bind(queueId).first<any>();if(!q||q.comment_id!==d.comment_id)return new Response('Queue item not found',{status:404});const now=Date.now(),visibility=action==='RESTORE'?'VISIBLE':'MOD_REMOVED';await c.env.DB.batch([c.env.DB.prepare('UPDATE comments SET visibility_status=?,moderation_reason=?,moderated_at=? WHERE id=?').bind(visibility,d.reason.trim(),now,q.comment_id),c.env.DB.prepare(`UPDATE moderation_queue SET status='REVIEWED',reviewed_at=?,reviewed_by=? WHERE id=?`).bind(now,c.user.id,queueId),c.env.DB.prepare('INSERT INTO moderation_actions(id,comment_id,moderator_user_id,action,reason,created_at) VALUES(?,?,?,?,?,?)').bind(randomId(),q.comment_id,c.user.id,action,d.reason.trim(),now),c.env.DB.prepare('INSERT INTO audit_events(id,actor_user_id,event_type,object_type,object_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(randomId(),c.user.id,`COMMENT_${action}`,'COMMENT',q.comment_id,JSON.stringify({reason:d.reason.trim(),queueId}),now)]);return redirect('/admin/moderation');}
