import type { RequestContext } from './types';
import { InvestigationRepository } from './investigationRepository';
import { CommunityRepository } from './communityRepository';
import { layout,time } from './views';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const rich=(s:unknown)=>esc(s).replace(/(^|\s)@([a-zA-Z0-9_.-]{2,40})/g,'$1<a class="mention" href="/u/$2">@$2</a>');
const html=(b:string,u:RequestContext['user'],s=200)=>new Response(b,{status:s,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':u?'private,no-store':'public,max-age=10,s-maxage=30,stale-while-revalidate=60','Vary':'Cookie'}});
export async function postV3(c:RequestContext,slug:string,id:string){
 const r=new InvestigationRepository(c.db),inv=await r.bySlug(slug,c.user?.id||'');if(!inv)return html(layout('Not found','<div class="page-shell page-content"><h1>Investigation not found</h1></div>',c.user),c.user,404);
 const post=await r.post(id,c.user?.id||'');if(!post||post.investigation_id!==inv.id)return html(layout('Not found','<div class="page-shell page-content"><h1>Post not found</h1></div>',c.user),c.user,404);
 const cr=new CommunityRepository(c.db),role=c.user?await cr.role(c.user.id,inv.id):null,canModerate=!!(c.user&&(c.user.isAdmin||role));
 const replies=await r.replies(id,c.user?.id||'',80),map=new Map<string,any[]>();for(const x of replies.rows){const k=x.parent_id||id;if(!map.has(k))map.set(k,[]);map.get(k)!.push(x);}
 const toolbar=(x:any)=>{const visible=x.visibility_status==='VISIBLE';return `<div class="comment-toolbar">${visible?(c.user?`<form method="post" action="/api/comments/${esc(x.id)}/like" data-async-like><button class="like-button ${x.liked?'liked':''}" aria-label="${x.liked?'Unlike':'Like'} comment"><span class="thumb">♡</span><span data-like-count>${Number(x.like_count)||0}</span></button></form><button type="button" class="reply-button inline-reply-toggle">Reply</button>`:`<a class="reply-button" href="/login?return=${encodeURIComponent(c.url.pathname)}">Reply</a>`):''}<details class="comment-more"><summary aria-label="More actions">•••</summary><div class="comment-menu">${c.user?.id===x.author_user_id?`<a href="/comments/${esc(x.id)}/edit">Edit</a>`:''}<button type="button" data-share-url="${c.env.APP_ORIGIN}/comments/${esc(x.id)}">Share</button><form method="post" action="/api/objects/COMMENT/${esc(x.id)}/save" data-async-save><button>Save</button></form>${visible?`<a href="/report/${esc(x.id)}">Report</a>`:''}${canModerate?`<form method="post" action="/api/comments/${esc(x.id)}/moderate"><input type="hidden" name="action" value="${visible?'REMOVE':'RESTORE'}"><button>${visible?'Remove':'Restore'}</button></form>`:''}</div></details></div>`;};
 const reply=(x:any,depth=0):string=>{const visible=x.visibility_status==='VISIBLE',body=visible?rich(x.content):'[Removed by moderation]',kids=map.get(x.id)||[];return `<article class="comment-thread" id="comment-${esc(x.id)}"><div class="comment-card"><div class="comment-who"><a href="/u/${encodeURIComponent(x.username)}">@${esc(x.username)}</a> · ${time(x.created_at)}</div><div class="comment-body">${body}</div>${toolbar(x)}${c.user&&visible?`<form class="inline-reply-form" method="post" action="/api/investigations/${esc(inv.id)}/comments" hidden><input type="hidden" name="parent_id" value="${esc(x.id)}"><textarea name="content" required maxlength="25000" rows="2" placeholder="Write a reply…"></textarea><div class="inline-reply-actions"><button type="button" class="reply-cancel">Cancel</button><button class="blue">Reply</button></div></form>`:''}</div>${kids.length?`<div class="comment-children depth-${Math.min(depth+1,4)}">${kids.map(y=>reply(y,depth+1)).join('')}</div>`:''}</article>`;};
 const visible=post.visibility_status==='VISIBLE',body=visible?rich(post.content):'[Removed by moderation]',children=map.get(id)||[];
 const composer=c.user&&visible?`<form class="comment-composer" method="post" action="/api/investigations/${esc(inv.id)}/comments"><input type="hidden" name="parent_id" value="${esc(id)}"><textarea name="content" required maxlength="25000" rows="4" placeholder="Add a comment…"></textarea><div class="composer-foot"><small>25,000 characters max</small><button class="blue">Comment</button></div></form>`:`<a class="quiet-action" href="/login?return=${encodeURIComponent(c.url.pathname)}">Log in to comment</a>`;
 return html(layout(post.description||inv.title,`<div class="page-shell post-page"><a class="post-back" href="/investigations/${encodeURIComponent(inv.slug)}?section=discussion#post-${esc(id)}">‹ ${esc(inv.title)}</a><article class="opened-post"><div class="comment-who"><a href="/u/${encodeURIComponent(post.username)}">@${esc(post.username)}</a> · ${time(post.created_at)}${post.tag_name?` · <b class="comment-tag">${esc(post.tag_name)}</b>`:''}</div><h1>${esc(post.description||'Post')}</h1><div class="opened-post-body">${body}</div>${toolbar(post)}</article><section class="post-comments"><div class="section-title-row"><h2>Comments</h2><span>${Number(post.reply_count)||0}</span></div>${composer}<div class="thread-list">${children.map(x=>reply(x)).join('')||'<div class="empty compact-empty">No comments yet.</div>'}</div>${replies.rows.length>=80?'<div class="notice">More replies exist. Additional reply pagination is being preserved rather than loading the entire thread at once.</div>':''}</section></div>`,c.user,post.content?.slice(0,180),`${c.env.APP_ORIGIN}/investigations/${encodeURIComponent(inv.slug)}/posts/${encodeURIComponent(id)}`),c.user);
}
