import type { RequestContext } from './types';
import { InvestigationRepository } from './investigationRepository';
import { CommunityRepository } from './communityRepository';
import { layout,time,friendShareHref } from './views';import { ClaimRepository } from './claimRepository';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const rich=(s:unknown)=>esc(s).replace(/(^|\s)@([a-zA-Z0-9_.-]{2,40})/g,'$1<a class="mention" href="/u/$2">@$2</a>');
const html=(b:string,u:RequestContext['user'],s=200)=>new Response(b,{status:s,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':u?'private,no-store':'public,max-age=10,s-maxage=30,stale-while-revalidate=60','Vary':'Cookie'}});
const flair=(v:unknown)=>String(v??'').toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,40);
const stateClass=(v:unknown)=>String(v??'UNVERIFIED').toLowerCase().replace(/[^a-z0-9-]/g,'-');
const thumbIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.5 21H4.8A1.8 1.8 0 0 1 3 19.2v-8.4A1.8 1.8 0 0 1 4.8 9h2.7m0 12h9.2a3 3 0 0 0 2.9-2.2l1.3-5A3 3 0 0 0 18 10h-4.2l.7-3.3A3.1 3.1 0 0 0 11.5 3L7.5 9v12Z"/></svg>';
const cursor=(raw:string|null)=>{const m=(raw||'').match(/^(\d{1,16})\.([a-zA-Z0-9-]{1,80})$/);if(!m)return undefined;const at=Number(m[1]);return Number.isSafeInteger(at)?{at,id:m[2]}:undefined;};
export async function postV3(c:RequestContext,slug:string,id:string){
 const r=new InvestigationRepository(c.db),inv=await r.bySlug(slug,c.user?.id||'');if(!inv)return html(layout('Not found','<div class="page-shell page-content"><h1>Investigation not found</h1></div>',c.user),c.user,404);
 const post=await r.post(id,c.user?.id||'');if(!post||post.investigation_id!==inv.id)return html(layout('Not found','<div class="page-shell page-content"><h1>Post not found</h1></div>',c.user),c.user,404);
 const cr=new CommunityRepository(c.db),claimsRepo=new ClaimRepository(c.db),role=c.user?await cr.role(c.user.id,inv.id):null,canModerate=!!(c.user&&(c.user.isAdmin||role)),sort=(c.url.searchParams.get('sort')||'BEST').toUpperCase(),before=cursor(c.url.searchParams.get('before'));
 const [postEvidence,postClaims]=await Promise.all([cr.contentEvidence(id,12),claimsRepo.forComment(id,12)]);const top=await r.topComments(id,c.user?.id||'',21,sort,before),page=top.rows.slice(0,20),previews=await r.replyPreviews(id,c.user?.id||'',page.map(x=>x.id),3),map=new Map<string,any[]>();for(const x of previews.rows){if(!map.has(x.parent_id))map.set(x.parent_id,[]);map.get(x.parent_id)!.push(x);}
 const intelligence=(target:string)=>c.user?`<details class="composer-intelligence"><summary>＋ Add intelligence</summary><div class="composer-intelligence-panel"><form method="post" action="/api/comments/${esc(target)}/claims"><label>Mark a claim</label><textarea name="statement" required maxlength="1000" rows="2" placeholder="Specific factual assertion…"></textarea><button class="quiet-action">Create unverified claim</button></form><form method="post" action="/api/comments/${esc(target)}/evidence"><label>Reference evidence ID</label><input name="evidence_id" required placeholder="Evidence ID"><button class="quiet-action">Attach evidence</button></form></div></details>`:'';
 const toolbar=(x:any,action:'reply'|'comment'|'none'='reply')=>{const visible=x.visibility_status==='VISIBLE',login=encodeURIComponent(c.url.pathname);return `<div class="comment-toolbar interaction-row">${visible?(c.user?`<form method="post" action="/api/comments/${esc(x.id)}/like" data-async-like><button class="like-button ${x.liked?'liked':''}" aria-label="${x.liked?'Unlike':'Like'} contribution"><span class="thumb">${thumbIcon}</span><span data-like-count>${Number(x.like_count)||0}</span></button></form>${action==='reply'?'<button type="button" class="reply-button inline-reply-toggle">Reply</button>':action==='comment'?'<button type="button" class="reply-button composer-toggle" data-composer-target="post-comment-composer">Comment</button>':''}`:`${action!=='none'?'<a class="reply-button" href="/login?return='+login+'">'+(action==='comment'?'Comment':'Reply')+'</a>':''}`):''}<button type="button" class="reply-button share-action" data-share-url="${c.env.APP_ORIGIN}/comments/${esc(x.id)}">Share</button>${c.user?`<a class="reply-button" href="${friendShareHref('COMMENT',String(x.id),'/comments/'+encodeURIComponent(String(x.id)))}">Send</a><form class="interaction-save" method="post" action="/api/objects/COMMENT/${esc(x.id)}/save" data-async-save><button>Save</button></form>`:''}<details class="comment-more"><summary aria-label="More actions">•••</summary><div class="comment-menu">${c.user?.id===x.author_user_id?`<a href="/comments/${esc(x.id)}/edit">Edit</a>`:''}${visible?`<a href="/report/${esc(x.id)}">Report</a>`:''}${canModerate?`<form method="post" action="/api/comments/${esc(x.id)}/moderate"><input type="hidden" name="action" value="${visible?'REMOVE':'RESTORE'}"><button>${visible?'Remove':'Restore'}</button></form>`:''}</div></details></div>`;};
 const card=(x:any,preview=false):string=>{const visible=x.visibility_status==='VISIBLE',kids=map.get(x.id)||[],remaining=Math.max(0,Number(x.reply_count||0)-kids.length),body=visible?rich(x.content):'[Removed by moderation]';return `<article class="comment-thread${preview?' reply-preview':''}" data-depth="${Math.min(4,Number(x.depth)||1)}" id="comment-${esc(x.id)}"><div class="comment-card thread-card" data-flair="${esc(flair(x.tag_name))}"><div class="comment-who"><a href="/u/${encodeURIComponent(x.username)}">@${esc(x.username)}</a> · ${time(x.created_at)}${x.tag_name?` · <span class="comment-tag">${esc(x.tag_name)}</span>`:''}</div><div class="comment-body">${body}</div>${toolbar(x)}${c.user&&visible?`<form class="inline-reply-form thread-composer" method="post" action="/api/investigations/${esc(inv.id)}/comments" hidden><input type="hidden" name="parent_id" value="${esc(x.id)}"><div class="composer-context">Replying to @${esc(x.username)}</div><textarea name="content" required maxlength="25000" rows="2" placeholder="Write a reply…"></textarea>${intelligence(x.id)}<div class="inline-reply-actions"><button type="button" class="reply-cancel">Cancel</button><button class="blue">Reply</button></div></form>`:''}</div>${kids.length?`<div class="comment-children">${kids.map(y=>card(y,true)).join('')}${remaining?`<a class="thread-more" href="/comments/${esc(x.id)}/thread">View ${remaining} more ${remaining===1?'reply':'replies'}</a>`:''}</div>`:Number(x.reply_count)>0?`<a class="thread-more" href="/comments/${esc(x.id)}/thread">View ${Number(x.reply_count)} ${Number(x.reply_count)===1?'reply':'replies'}</a>`:''}</article>`;};
 const visible=post.visibility_status==='VISIBLE',body=visible?rich(post.content):'[Removed by moderation]';
 const composer=c.user&&visible?`<form id="post-comment-composer" class="comment-composer thread-composer post-comment-composer" method="post" action="/api/investigations/${esc(inv.id)}/comments" hidden><input type="hidden" name="parent_id" value="${esc(id)}"><div class="composer-context">Comment on this post</div><textarea name="content" required maxlength="25000" rows="3" placeholder="Add a comment…"></textarea>${intelligence(id)}<div class="composer-foot"><button type="button" class="reply-cancel composer-cancel">Cancel</button><button class="blue">Comment</button></div></form>`:'';
 const sorts=['BEST','TOP','NEW','OLD'].map(x=>`<a class="${sort===x?'active':''}" href="/investigations/${encodeURIComponent(inv.slug)}/posts/${esc(id)}?sort=${x.toLowerCase()}">${x[0]+x.slice(1).toLowerCase()}</a>`).join('');
 const last=page.at(-1),more=top.rows.length>20&&last&&(sort==='NEW'||sort==='OLD')?`<p class="pagination"><a class="quiet-action" href="?sort=${sort.toLowerCase()}&before=${Number(last.created_at)}.${encodeURIComponent(String(last.id))}">Load more comments</a></p>`:'';
 return html(layout(post.description||inv.title,`<div class="page-shell post-page" data-recent-type="POST" data-recent-id="${esc(id)}" data-recent-label="${esc(post.description||'Post')}"><a class="post-back" href="/investigations/${encodeURIComponent(inv.slug)}?section=posts#post-${esc(id)}">‹ ${esc(inv.title)}</a><article class="opened-post" data-flair="${esc(flair(post.tag_name))}"><div class="comment-who"><a href="/u/${encodeURIComponent(post.username)}">@${esc(post.username)}</a> · ${time(post.created_at)}${post.tag_name?` · <a class="comment-tag" href="/investigations/${encodeURIComponent(inv.slug)}?section=posts&flair=${encodeURIComponent(post.tag_name)}">${esc(post.tag_name)}</a>`:''}</div><h1>${esc(post.description||'Post')}</h1><div class="opened-post-body">${body}</div>${postEvidence.rows.length?`<div class="content-sources"><b>${postEvidence.rows.length} source${postEvidence.rows.length===1?'':'s'}</b>${postEvidence.rows.map((e:any)=>`<a class="source-link verification-${esc(stateClass(e.verification_state))}" href="/evidence/${esc(e.id)}"><span class="source-mark" aria-hidden="true">▤</span><span>${esc(e.title)} <small>${esc(String(e.verification_state||'UNVERIFIED').replaceAll('_',' '))}</small></span></a>`).join('')}</div>`:''}${postClaims.rows.map((cl:any)=>`<div class="claim-card claim-${esc(stateClass(cl.status))}"><div class="type">CLAIM · ${esc(cl.status)}</div><p>${esc(cl.statement)}</p><div class="meta">${Number(cl.supports)} supporting · ${Number(cl.contradicts)} contradicting</div></div>`).join('')}${toolbar(post,'comment')}${composer}</article><section class="post-comments"><div class="section-title-row"><h2>Comments</h2><span>${Number(post.reply_count)||0}</span></div><nav class="comment-sort" aria-label="Comment sorting">${sorts}</nav><div class="thread-list">${page.map(x=>card(x)).join('')||'<div class="empty compact-empty">No comments yet.</div>'}</div>${more}</section></div>`,c.user,post.content?.slice(0,180),`${c.env.APP_ORIGIN}/investigations/${encodeURIComponent(inv.slug)}/posts/${encodeURIComponent(id)}`),c.user);
}
export async function commentThreadV3(c:RequestContext,id:string){
 const cr=new CommunityRepository(c.db),target=await cr.commentContext(id,c.user?.id||'');if(!target)return html(layout('Not found','<div class="page-shell page-content"><h1>Comment not found</h1></div>',c.user),c.user,404);
 const r=new InvestigationRepository(c.db),inv=await r.bySlug(target.slug,c.user?.id||'');if(!inv)return html(layout('Not found','<div class="page-shell page-content"><h1>Investigation not found</h1></div>',c.user),c.user,404);
 const before=cursor(c.url.searchParams.get('before')),children=await r.children(id,c.user?.id||'',31,before),page=children.rows.slice(0,30),last=page.at(-1),visible=target.visibility_status==='VISIBLE';
 const like=(x:any)=>c.user&&x.visibility_status==='VISIBLE'?`<form method="post" action="/api/comments/${esc(x.id)}/like" data-async-like><button class="like-button ${x.liked?'liked':''}" aria-label="${x.liked?'Unlike':'Like'} contribution"><span class="thumb">${thumbIcon}</span><span data-like-count>${Number(x.like_count)||0}</span></button></form>`:`<span class="like-button readonly-like"><span class="thumb">${thumbIcon}</span><span>${Number(x.like_count)||0}</span></span>`;
 const actions=(x:any)=>`<div class="comment-toolbar interaction-row">${like(x)}<a class="reply-button" href="/investigations/${encodeURIComponent(target.slug)}/posts/${encodeURIComponent(target.root_id||target.id)}#comment-${esc(x.id)}">Reply</a><button type="button" class="reply-button" data-share-url="${c.env.APP_ORIGIN}/comments/${esc(x.id)}">Share</button><a class="reply-button" href="/comments/${esc(x.id)}/thread">Open thread</a></div>`;
 const rows=page.map(x=>`<article class="comment-thread thread-focus-child" id="comment-${esc(x.id)}"><div class="comment-card thread-card" data-flair="${esc(flair(x.tag_name))}"><div class="comment-who"><a href="/u/${encodeURIComponent(x.username)}">@${esc(x.username)}</a> · ${time(x.created_at)}</div><div class="comment-body">${x.visibility_status==='VISIBLE'?rich(x.content):'[Removed by moderation]'}</div>${actions(x)}</div></article>`).join('')||'<div class="empty">No replies yet.</div>';
 const more=children.rows.length>30&&last?`<p class="pagination"><a class="quiet-action" href="?before=${Number(last.created_at)}.${encodeURIComponent(String(last.id))}">Load more replies</a></p>`:'';
 const targetBody=visible?rich(target.content):'[Removed by moderation]';
 return html(layout('Comment thread',`<div class="page-shell post-page thread-focus-page"><a class="post-back" href="/investigations/${encodeURIComponent(target.slug)}/posts/${encodeURIComponent(target.root_id||target.id)}#comment-${esc(id)}">‹ Back to post</a><article class="focused-comment thread-card" data-flair="${esc(flair(target.tag_name))}"><div class="comment-who"><a href="/u/${encodeURIComponent(target.username)}">@${esc(target.username)}</a> · ${time(target.created_at)}${target.tag_name?` · <span class="comment-tag">${esc(target.tag_name)}</span>`:''}</div><div class="comment-body">${targetBody}</div>${actions(target)}</article><div class="thread-focus-heading"><h1>Replies</h1><span>${Number(target.reply_count)||0}</span></div><div class="thread-focus-children">${rows}</div>${more}</div>`,c.user),c.user);
}
