import type { RequestContext } from './types';
import { InvestigationRepository } from './investigationRepository';
import { CommunityRepository } from './communityRepository';
import { layout,time } from './views';import { ClaimRepository } from './claimRepository';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const rich=(s:unknown)=>esc(s).replace(/(^|\s)@([a-zA-Z0-9_.-]{2,40})/g,'$1<a class="mention" href="/u/$2">@$2</a>');
const html=(b:string,u:RequestContext['user'],s=200)=>new Response(b,{status:s,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':u?'private,no-store':'public,max-age=10,s-maxage=30,stale-while-revalidate=60','Vary':'Cookie'}});
const cursor=(raw:string|null)=>{const m=(raw||'').match(/^(\d{1,16})\.([a-zA-Z0-9-]{1,80})$/);if(!m)return undefined;const at=Number(m[1]);return Number.isSafeInteger(at)?{at,id:m[2]}:undefined;};
export async function postV3(c:RequestContext,slug:string,id:string){
 const r=new InvestigationRepository(c.db),inv=await r.bySlug(slug,c.user?.id||'');if(!inv)return html(layout('Not found','<div class="page-shell page-content"><h1>Investigation not found</h1></div>',c.user),c.user,404);
 const post=await r.post(id,c.user?.id||'');if(!post||post.investigation_id!==inv.id)return html(layout('Not found','<div class="page-shell page-content"><h1>Post not found</h1></div>',c.user),c.user,404);
 const cr=new CommunityRepository(c.db),claimsRepo=new ClaimRepository(c.db),role=c.user?await cr.role(c.user.id,inv.id):null,canModerate=!!(c.user&&(c.user.isAdmin||role)),sort=(c.url.searchParams.get('sort')||'BEST').toUpperCase(),before=cursor(c.url.searchParams.get('before'));
 const [postEvidence,postClaims]=await Promise.all([cr.contentEvidence(id,12),claimsRepo.forComment(id,12)]);const top=await r.topComments(id,c.user?.id||'',21,sort,before),page=top.rows.slice(0,20),previews=await r.replyPreviews(id,c.user?.id||'',page.map(x=>x.id),3),map=new Map<string,any[]>();for(const x of previews.rows){if(!map.has(x.parent_id))map.set(x.parent_id,[]);map.get(x.parent_id)!.push(x);}
 const toolbar=(x:any,allowReply=true)=>{const visible=x.visibility_status==='VISIBLE';return `<div class="comment-toolbar">${visible?(c.user?`<form method="post" action="/api/comments/${esc(x.id)}/like" data-async-like><button class="like-button ${x.liked?'liked':''}" aria-label="${x.liked?'Unlike':'Like'} contribution"><span class="thumb">△</span><span data-like-count>${Number(x.like_count)||0}</span></button></form>${allowReply?'<button type="button" class="reply-button inline-reply-toggle">Reply</button>':''}`:(allowReply?`<a class="reply-button" href="/login?return=${encodeURIComponent(c.url.pathname)}">Reply</a>`:'')):''}<details class="comment-more"><summary aria-label="More actions">•••</summary><div class="comment-menu">${c.user?.id===x.author_user_id?`<a href="/comments/${esc(x.id)}/edit">Edit</a>`:''}<button type="button" data-share-url="${c.env.APP_ORIGIN}/comments/${esc(x.id)}">Share</button><form method="post" action="/api/objects/COMMENT/${esc(x.id)}/save" data-async-save><button>Save</button></form>${visible?`<a href="/report/${esc(x.id)}">Report</a>`:''}${canModerate?`<form method="post" action="/api/comments/${esc(x.id)}/moderate"><input type="hidden" name="action" value="${visible?'REMOVE':'RESTORE'}"><button>${visible?'Remove':'Restore'}</button></form>`:''}</div></details></div>`;};
 const card=(x:any,preview=false):string=>{const visible=x.visibility_status==='VISIBLE',kids=map.get(x.id)||[],remaining=Math.max(0,Number(x.reply_count||0)-kids.length),body=visible?rich(x.content):'[Removed by moderation]';return `<article class="comment-thread${preview?' reply-preview':''}" id="comment-${esc(x.id)}"><div class="comment-card"><div class="comment-who"><a href="/u/${encodeURIComponent(x.username)}">@${esc(x.username)}</a> · ${time(x.created_at)}</div><div class="comment-body">${body}</div>${toolbar(x)}${c.user&&visible?`<form class="inline-reply-form" method="post" action="/api/investigations/${esc(inv.id)}/comments" hidden><input type="hidden" name="parent_id" value="${esc(x.id)}"><textarea name="content" required maxlength="25000" rows="2" placeholder="Write a reply…"></textarea><div class="inline-reply-actions"><button type="button" class="reply-cancel">Cancel</button><button class="blue">Reply</button></div></form>`:''}</div>${kids.length?`<div class="comment-children">${kids.map(y=>card(y,true)).join('')}${remaining?`<a class="thread-more" href="/comments/${esc(x.id)}/thread">View ${remaining} more ${remaining===1?'reply':'replies'}</a>`:''}</div>`:Number(x.reply_count)>0?`<a class="thread-more" href="/comments/${esc(x.id)}/thread">View ${Number(x.reply_count)} ${Number(x.reply_count)===1?'reply':'replies'}</a>`:''}</article>`;};
 const visible=post.visibility_status==='VISIBLE',body=visible?rich(post.content):'[Removed by moderation]';
 const composer=c.user&&visible?`<form class="comment-composer" method="post" action="/api/investigations/${esc(inv.id)}/comments"><input type="hidden" name="parent_id" value="${esc(id)}"><textarea name="content" required maxlength="25000" rows="4" placeholder="Add a comment…"></textarea><div class="composer-foot"><small>25,000 characters max</small><button class="blue">Comment</button></div></form>`:`<a class="quiet-action" href="/login?return=${encodeURIComponent(c.url.pathname)}">Log in to comment</a>`;
 const sorts=['BEST','TOP','NEW','OLD'].map(x=>`<a class="${sort===x?'active':''}" href="/investigations/${encodeURIComponent(inv.slug)}/posts/${esc(id)}?sort=${x.toLowerCase()}">${x[0]+x.slice(1).toLowerCase()}</a>`).join('');
 const last=page.at(-1),more=top.rows.length>20&&last&&(sort==='NEW'||sort==='OLD')?`<p class="pagination"><a class="quiet-action" href="?sort=${sort.toLowerCase()}&before=${Number(last.created_at)}.${encodeURIComponent(String(last.id))}">Load more comments</a></p>`:'';
 return html(layout(post.description||inv.title,`<div class="page-shell post-page" data-recent-type="POST" data-recent-id="${esc(id)}" data-recent-label="${esc(post.description||'Post')}"><a class="post-back" href="/investigations/${encodeURIComponent(inv.slug)}?section=posts#post-${esc(id)}">‹ ${esc(inv.title)}</a><article class="opened-post"><div class="comment-who"><a href="/u/${encodeURIComponent(post.username)}">@${esc(post.username)}</a> · ${time(post.created_at)}${post.tag_name?` · <a class="comment-tag" href="/investigations/${encodeURIComponent(inv.slug)}?section=posts&flair=${encodeURIComponent(post.tag_name)}">${esc(post.tag_name)}</a>`:''}</div><h1>${esc(post.description||'Post')}</h1><div class="opened-post-body">${body}</div>${postEvidence.rows.length?`<div class="content-sources"><b>${postEvidence.rows.length} source${postEvidence.rows.length===1?'':'s'}</b>${postEvidence.rows.map((e:any)=>`<a href="/evidence/${esc(e.id)}">${esc(e.title)} · ${esc(String(e.verification_state||'UNVERIFIED').replaceAll('_',' '))}</a>`).join('')}</div>`:''}${postClaims.rows.map((cl:any)=>`<div class="claim-card"><div class="type">CLAIM · ${esc(cl.status)}</div><p>${esc(cl.statement)}</p><div class="meta">${Number(cl.supports)} supporting · ${Number(cl.contradicts)} contradicting</div></div>`).join('')}${c.user&&visible?`<details class="intelligence-add"><summary>Add intelligence</summary><form method="post" action="/api/comments/${esc(id)}/claims"><label>Mark a claim</label><textarea name="statement" required maxlength="1000" rows="2" placeholder="Specific factual assertion…"></textarea><button class="quiet-action">Create unverified claim</button></form><form method="post" action="/api/comments/${esc(id)}/evidence"><label>Reference evidence ID</label><input name="evidence_id" required placeholder="Evidence ID"><button class="quiet-action">Attach evidence</button></form></details>`:''}${toolbar(post,false)}</article><section class="post-comments"><div class="section-title-row"><h2>Comments</h2><span>${Number(post.reply_count)||0}</span></div><nav class="comment-sort" aria-label="Comment sorting">${sorts}</nav>${composer}<div class="thread-list">${page.map(x=>card(x)).join('')||'<div class="empty compact-empty">No comments yet.</div>'}</div>${more}</section></div>`,c.user,post.content?.slice(0,180),`${c.env.APP_ORIGIN}/investigations/${encodeURIComponent(inv.slug)}/posts/${encodeURIComponent(id)}`),c.user);
}
export async function commentThreadV3(c:RequestContext,id:string){
 const cr=new CommunityRepository(c.db),target=await cr.commentContext(id);if(!target)return html(layout('Not found','<div class="page-shell page-content"><h1>Comment not found</h1></div>',c.user),c.user,404);
 const r=new InvestigationRepository(c.db),inv=await r.bySlug(target.slug,c.user?.id||'');if(!inv)return html(layout('Not found','<div class="page-shell page-content"><h1>Investigation not found</h1></div>',c.user),c.user,404);
 const before=cursor(c.url.searchParams.get('before')),children=await r.children(id,c.user?.id||'',31,before),page=children.rows.slice(0,30),last=page.at(-1);
 const rows=page.map(x=>`<article class="comment-thread" id="comment-${esc(x.id)}"><div class="comment-card"><div class="comment-who"><a href="/u/${encodeURIComponent(x.username)}">@${esc(x.username)}</a> · ${time(x.created_at)}</div><div class="comment-body">${x.visibility_status==='VISIBLE'?rich(x.content):'[Removed by moderation]'}</div><a class="thread-more" href="/comments/${esc(x.id)}/thread">${Number(x.reply_count)||0} replies · open thread</a></div></article>`).join('')||'<div class="empty">No replies yet.</div>';
 const more=children.rows.length>30&&last?`<p class="pagination"><a class="quiet-action" href="?before=${Number(last.created_at)}.${encodeURIComponent(String(last.id))}">Load more replies</a></p>`:'';
 return html(layout('Comment thread',`<div class="page-shell post-page"><a class="post-back" href="/investigations/${encodeURIComponent(target.slug)}/posts/${encodeURIComponent(target.root_id||target.id)}#comment-${esc(id)}">‹ Back to post</a><div class="eyebrow">COMMENT THREAD</div><h1>Replies</h1>${rows}${more}</div>`,c.user),c.user);
}
