import type { IntelDatabase } from './db/types';
export type Visibility='PUBLIC'|'FRIENDS'|'PRIVATE';
const pair=(a:string,b:string)=>a<b?[a,b]:[b,a];
export class SocialRepository{
 constructor(private db:IntelDatabase){}
 async searchUsers(me:string,q:string,limit=12){const prefix=q.slice(0,Math.max(1,q.length-1));return this.db.execute<any>(`SELECT id,username,avatar_object_key FROM users WHERE status='ACTIVE' AND id<>? AND username_norm>=? AND username_norm<? AND NOT EXISTS(SELECT 1 FROM friendships f WHERE f.user_low_id=min(?,users.id) AND f.user_high_id=max(?,users.id) AND f.status='BLOCKED') ORDER BY username_norm LIMIT ?`,[me,prefix,prefix+'\uffff',me,me,Math.min(40,limit)]);}
 friendship(a:string,b:string){const [lo,hi]=pair(a,b);return this.db.first<any>('SELECT * FROM friendships WHERE user_low_id=? AND user_high_id=? LIMIT 1',[lo,hi]);}
 async requestFriend(me:string,other:string,now:number){const[lo,hi]=pair(me,other);if(me===other)throw new Error('SELF');const existing=await this.friendship(me,other);if(existing?.status==='BLOCKED')throw new Error('BLOCKED');if(existing?.status==='FRIENDS'||existing?.status==='PENDING')return existing;await this.db.execute("INSERT INTO friendships(user_low_id,user_high_id,requested_by,status,created_at,updated_at) VALUES(?,?,?,'PENDING',?,?)",[lo,hi,me,now,now]);return this.friendship(me,other);}
 async respondFriend(me:string,other:string,action:'ACCEPT'|'DECLINE'|'BLOCK',now:number){const[lo,hi]=pair(me,other),f=await this.friendship(me,other);if(!f||f.status!=='PENDING'||f.requested_by===me)throw new Error('INVALID_REQUEST');if(action==='DECLINE'){await this.db.execute('DELETE FROM friendships WHERE user_low_id=? AND user_high_id=? AND status=?',[lo,hi,'PENDING']);return;}if(action==='BLOCK'){await this.db.batch([{sql:"UPDATE friendships SET status='BLOCKED',blocked_by=?,updated_at=? WHERE user_low_id=? AND user_high_id=?",args:[me,now,lo,hi]},{sql:'DELETE FROM user_follows WHERE (follower_user_id=? AND followed_user_id=?) OR (follower_user_id=? AND followed_user_id=?)',args:[me,other,other,me]}]);return;}await this.db.execute("UPDATE friendships SET status='FRIENDS',blocked_by=NULL,updated_at=? WHERE user_low_id=? AND user_high_id=?",[now,lo,hi]);}
 async block(me:string,other:string,now:number){const[lo,hi]=pair(me,other);await this.db.batch([{sql:`INSERT INTO friendships(user_low_id,user_high_id,requested_by,status,blocked_by,created_at,updated_at) VALUES(?,?,?,'BLOCKED',?,?,?) ON CONFLICT(user_low_id,user_high_id) DO UPDATE SET status='BLOCKED',blocked_by=excluded.blocked_by,updated_at=excluded.updated_at`,args:[lo,hi,me,me,now,now]},{sql:'DELETE FROM user_follows WHERE (follower_user_id=? AND followed_user_id=?) OR (follower_user_id=? AND followed_user_id=?)',args:[me,other,other,me]}]);}
 async friends(me:string,limit=40){return this.db.execute<any>(`SELECT u.id,u.username,u.avatar_object_key,f.updated_at FROM friendships f JOIN users u ON u.id=CASE WHEN f.user_low_id=? THEN f.user_high_id ELSE f.user_low_id END WHERE (f.user_low_id=? OR f.user_high_id=?) AND f.status='FRIENDS' ORDER BY f.updated_at DESC LIMIT ?`,[me,me,me,Math.min(60,limit)]);}
 async pending(me:string){return this.db.execute<any>(`SELECT u.id,u.username,u.avatar_object_key,f.updated_at FROM friendships f JOIN users u ON u.id=f.requested_by WHERE (f.user_low_id=? OR f.user_high_id=?) AND f.status='PENDING' AND f.requested_by<>? ORDER BY f.updated_at DESC LIMIT 30`,[me,me,me]);}
 async ensureConversation(me:string,other:string,now:number){const f=await this.friendship(me,other);if(f?.status!=='FRIENDS')throw new Error('NOT_FRIENDS');const[lo,hi]=pair(me,other);let c=await this.db.first<any>('SELECT id FROM conversations WHERE user_low_id=? AND user_high_id=? LIMIT 1',[lo,hi]);if(c)return c.id;const id=crypto.randomUUID();try{await this.db.batch([{sql:'INSERT INTO conversations(id,user_low_id,user_high_id,updated_at) VALUES(?,?,?,?)',args:[id,lo,hi,now]},{sql:'INSERT INTO conversation_members(conversation_id,user_id) VALUES(?,?)',args:[id,lo]},{sql:'INSERT INTO conversation_members(conversation_id,user_id) VALUES(?,?)',args:[id,hi]}]);return id;}catch{c=await this.db.first<any>('SELECT id FROM conversations WHERE user_low_id=? AND user_high_id=? LIMIT 1',[lo,hi]);if(c)return c.id;throw new Error('CONVERSATION_CREATE');}}
 member(conversationId:string,userId:string){return this.db.first<any>(`SELECT c.*,u.id other_id,u.username other_username,u.avatar_object_key other_avatar FROM conversations c JOIN friendships f ON f.user_low_id=c.user_low_id AND f.user_high_id=c.user_high_id AND f.status='FRIENDS' JOIN conversation_members cm ON cm.conversation_id=c.id AND cm.user_id=? JOIN users u ON u.id=CASE WHEN c.user_low_id=? THEN c.user_high_id ELSE c.user_low_id END WHERE c.id=? LIMIT 1`,[userId,userId,conversationId]);}
 async conversations(me:string,limit=31,before?:{at:number,id:string}){const cur=before?' AND (c.updated_at<? OR (c.updated_at=? AND c.id<?))':'';const args:any[]=[me,me,me];if(before)args.push(before.at,before.at,before.id);args.push(Math.min(61,limit));return this.db.execute<any>(`SELECT c.id,c.updated_at,c.last_message_preview,c.last_message_id,u.username,u.avatar_object_key,cm.last_read_message_id FROM conversations c JOIN friendships f ON f.user_low_id=c.user_low_id AND f.user_high_id=c.user_high_id AND f.status='FRIENDS' JOIN conversation_members cm ON cm.conversation_id=c.id AND cm.user_id=? JOIN users u ON u.id=CASE WHEN c.user_low_id=? THEN c.user_high_id ELSE c.user_low_id END WHERE (c.user_low_id=? OR c.user_high_id=?)${cur} ORDER BY c.updated_at DESC,c.id DESC LIMIT ?`,[me,me,me,me,...(before?[before.at,before.at,before.id]:[]),Math.min(61,limit)]);}
 async messages(conversationId:string,me:string,limit=41,before?:{at:number,id:string}){if(!await this.member(conversationId,me))throw new Error('FORBIDDEN');const cur=before?' AND (m.created_at<? OR (m.created_at=? AND m.id<?))':'';const args:any[]=[conversationId];if(before)args.push(before.at,before.at,before.id);args.push(Math.min(61,limit));return this.db.execute<any>(`SELECT m.*,a.id attachment_id,a.original_filename,a.mime_type,a.size_bytes FROM private_messages m LEFT JOIN message_attachments a ON a.message_id=m.id WHERE m.conversation_id=?${cur} ORDER BY m.created_at DESC,m.id DESC LIMIT ?`,args);}
 attachmentUsage(userId:string,since:number){return this.db.first<any>('SELECT COUNT(*) files,COALESCE(SUM(a.size_bytes),0) bytes FROM message_attachments a JOIN private_messages m ON m.id=a.message_id WHERE m.sender_user_id=? AND a.created_at>=?',[userId,since]);}
 messageByNonce(userId:string,nonce:string){return this.db.first<any>('SELECT id,conversation_id,created_at FROM private_messages WHERE sender_user_id=? AND client_nonce=? LIMIT 1',[userId,nonce]);}
 async send(conversationId:string,me:string,body:string,nonce:string,now:number,shared?:{type?:string,id?:string,url?:string}){const member=await this.member(conversationId,me);if(!member)throw new Error('FORBIDDEN');const f=await this.friendship(me,member.other_id);if(f?.status!=='FRIENDS')throw new Error('NOT_FRIENDS');const existing=await this.db.first<any>('SELECT id,created_at FROM private_messages WHERE sender_user_id=? AND client_nonce=? LIMIT 1',[me,nonce]);if(existing)return existing;const id=crypto.randomUUID(),preview=(body||shared?.type||'Attachment').slice(0,120);await this.db.batch([{sql:'INSERT INTO private_messages(id,conversation_id,sender_user_id,client_nonce,body,shared_object_type,shared_object_id,shared_url,created_at) VALUES(?,?,?,?,?,?,?,?,?)',args:[id,conversationId,me,nonce,body,shared?.type||null,shared?.id||null,shared?.url||null,now]},{sql:'UPDATE conversations SET last_message_id=?,last_message_preview=?,updated_at=? WHERE id=?',args:[id,preview,now,conversationId]},{sql:'UPDATE conversation_members SET last_read_message_id=?,last_read_at=? WHERE conversation_id=? AND user_id=?',args:[id,now,conversationId,me]}]);return{id,created_at:now};}
 markRead(conversationId:string,me:string,messageId:string,now:number){return this.db.execute('UPDATE conversation_members SET last_read_message_id=?,last_read_at=? WHERE conversation_id=? AND user_id=?',[messageId,now,conversationId,me]);}
 async profile(viewer:string,target:string){const u=await this.db.first<any>('SELECT id,username,avatar_object_key,profile_visibility,created_at FROM users WHERE id=? AND status=? LIMIT 1',[target,'ACTIVE']);if(!u)return null;const f=viewer===target?null:await this.friendship(viewer,target);if(f?.status==='BLOCKED')return null;const canActivity=viewer===target||u.profile_visibility==='PUBLIC'||(u.profile_visibility==='FRIENDS'&&f?.status==='FRIENDS');return{...u,canActivity,isFriend:f?.status==='FRIENDS'};}
 setPrivacy(userId:string,v:Visibility,now:number){return this.db.batch([{sql:'UPDATE users SET profile_visibility=? WHERE id=?',args:[v,userId]},{sql:'INSERT INTO audit_events(id,actor_user_id,event_type,object_type,object_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)',args:[crypto.randomUUID(),userId,'PRIVACY_CHANGED','USER',userId,JSON.stringify({profileVisibility:v}),now]}]);}
 async notify(userId:string,type:string,payload:any,now:number){const p=await this.notificationPreferences(userId);const enabled=!!Number(p.in_app)&&(type==='FRIEND_REQUEST'?!!Number(p.friend_requests):type==='FRIEND_ACCEPTED'?!!Number(p.friend_accepts):type==='NEW_MESSAGE'?!!Number(p.messages):true);if(!enabled)return;await this.db.execute('INSERT INTO notifications(id,user_id,type,payload_json,created_at) VALUES(?,?,?,?,?)',[crypto.randomUUID(),userId,type,JSON.stringify(payload),now]);}
 async notificationPreferences(userId:string){return (await this.db.first<any>('SELECT friend_requests,friend_accepts,messages,in_app,push FROM social_notification_preferences WHERE user_id=? LIMIT 1',[userId]))||{friend_requests:1,friend_accepts:1,messages:1,in_app:1,push:1};}
 async setNotificationPreferences(userId:string,v:{friend_requests:number;friend_accepts:number;messages:number;in_app:number;push:number},now:number){await this.db.execute(`INSERT INTO social_notification_preferences(user_id,friend_requests,friend_accepts,messages,in_app,push,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET friend_requests=excluded.friend_requests,friend_accepts=excluded.friend_accepts,messages=excluded.messages,in_app=excluded.in_app,push=excluded.push,updated_at=excluded.updated_at`,[userId,v.friend_requests,v.friend_accepts,v.messages,v.in_app,v.push,now]);}
 async unreadCount(userId:string){const r=await this.db.first<any>("SELECT COUNT(*) n FROM notifications WHERE user_id=? AND read_at IS NULL AND type IN ('NEW_MESSAGE','FRIEND_REQUEST','FRIEND_ACCEPTED')",[userId]);return Math.min(99,Number(r?.n||0));}
 markFriendRequestNotificationsRead(userId:string,actorUserId:string,now:number){return this.db.execute("UPDATE notifications SET read_at=? WHERE user_id=? AND read_at IS NULL AND type='FRIEND_REQUEST' AND json_extract(payload_json,'$.actorUserId')=?",[now,userId,actorUserId]);}
 async markConversationNotificationsRead(userId:string,conversationId:string,now:number){return this.db.execute("UPDATE notifications SET read_at=? WHERE user_id=? AND read_at IS NULL AND type='NEW_MESSAGE' AND json_extract(payload_json,'$.conversationId')=?",[now,userId,conversationId]);}
 async pushDevices(userId:string){return this.db.execute<any>('SELECT id,endpoint,p256dh,auth FROM push_devices WHERE user_id=? AND enabled=1 ORDER BY updated_at DESC LIMIT 10',[userId]);}
 async savePushDevice(userId:string,v:{endpoint:string;p256dh:string;auth:string},now:number){const existing=await this.db.first<any>('SELECT id,user_id FROM push_devices WHERE endpoint=? LIMIT 1',[v.endpoint]);if(existing&&existing.user_id!==userId)throw new Error('ENDPOINT_OWNED');const id=existing?.id||crypto.randomUUID();await this.db.execute(`INSERT INTO push_devices(id,user_id,endpoint,p256dh,auth,enabled,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?) ON CONFLICT(endpoint) DO UPDATE SET p256dh=excluded.p256dh,auth=excluded.auth,enabled=1,updated_at=excluded.updated_at`,[id,userId,v.endpoint,v.p256dh,v.auth,now,now]);return id;}
 disablePushDevice(userId:string,endpoint:string,now:number){return this.db.execute('UPDATE push_devices SET enabled=0,updated_at=? WHERE user_id=? AND endpoint=?',[now,userId,endpoint]);}
}
