import {describe,expect,it} from 'vitest';import {readFileSync,existsSync} from 'node:fs';
const read=(p:string)=>readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
describe('INTEL final architecture contract',()=>{it('has no D1 runtime adapter, binding, provider switch, or scripts',()=>{expect(existsSync(new URL('../src/db/d1.ts',import.meta.url))).toBe(false);expect(read('wrangler.jsonc')).not.toMatch(/D1|PERSISTENCE_PROVIDER|d1_databases/);expect(read('package.json')).not.toMatch(/wrangler d1|db:legacy/);expect(read('src/types.ts')).not.toMatch(/D1Database|PERSISTENCE_PROVIDER/);expect(read('src/db/index.ts')).not.toMatch(/D1|PERSISTENCE_PROVIDER/);});it('keeps Turso migrations through investigation teams',()=>{expect(read('src/tursoProduction.ts')).toContain('0005_investigation_teams.sql');expect(read('migrations-turso/0005_investigation_teams.sql')).toContain('investigation_members');});});
describe('community product routing',()=>{const entry=read('src/entry.ts');it('exposes first-class community surfaces',()=>{for(const route of ["p==='/following'","p==='/notifications'","/^\\/u\\/([^/]+)$/","/^\\/relationships\\/([^/]+)$/","/evidence\\/new$/","/moderate$/"])expect(entry).toContain(route);});it('does not expose migration consoles',()=>{expect(entry).not.toContain('/system/turso-');expect(entry).not.toContain('bootstrapPage');});});
describe('authorization and evidence invariants',()=>{it('prevents self-promotion and requires owner role for team changes',()=>{const routes=read('src/communityRoutes.ts');expect(routes).toContain("target===c.user!.id");expect(routes).toContain("role?.role!=='OWNER'");});it('forces community evidence to unverified and uses R2',()=>{const upload=read('src/adminEvidence.ts');expect(upload).toContain("community?'UNVERIFIED':requested");expect(upload).toContain('storeEvidence(c.env,file,key)');expect(upload).toContain('20*1024*1024');});it('enforces same-origin on community writes',()=>{const routes=read('src/communityRoutes.ts');expect(routes.match(/validSameOrigin/g)?.length).toBeGreaterThanOrEqual(5);});});
describe('navigation and search contracts',()=>{it('uses dedicated mobile destinations',()=>{const views=read('src/views.ts');expect(views).toContain('href="/following"');expect(views).toContain('href="/notifications"');expect(views).toContain('<span>Notifications</span>');});it('search filters change FTS query and relationships deep-link',()=>{expect(read('src/searchRepository.ts')).toContain('s.object_type=?');const routes=read('src/searchRoutes.ts');expect(routes).toContain("'RELATIONSHIP'");expect(routes).toContain('/relationships/');});});

describe('bugfix hardening regressions',()=>{it('uses a modern PBKDF2 cost while retaining per-credential parameters',()=>{expect(read('src/security.ts')).toContain('DEFAULT_PBKDF2_ITERATIONS=210000');expect(read('src/accountRepository.ts')).toContain('password_salt,kdf_params');});it('protects unpublished evidence attachments',()=>{const repo=read('src/dashboardRepository.ts');expect(repo).toContain('JOIN evidence e');expect(repo).toContain('i.published_at IS NOT NULL');expect(read('src/dashboardRoutes.ts')).not.toContain("h.set('Digest'");});it('loads password controls only on password-bearing surfaces',()=>{expect(read('src/views.ts')).not.toContain('/auth.js');expect(read('src/authRoutes.ts')).toContain('/auth.js');expect(read('src/account.ts')).toContain('/auth.js');});it('validates community mutation targets before writes',()=>{const routes=read('src/communityRoutes.ts');expect(routes).toContain('Comment is not available');expect(routes).toContain('followerRole(target,id)');expect(routes).toContain('if(membership)return redirect(back(c))');});it('uses a search canonical instead of the home canonical',()=>{expect(read('src/searchRoutes.ts')).toContain('/search`');});});

describe('community completion refinement',()=>{it('publishes relevant legal terms and registration notice',()=>{const legal=read('src/legalRoutes.ts'),entry=read('src/entry.ts'),auth=read('src/authRoutes.ts');expect(legal).toContain('Terms of Service');expect(legal).toContain('Terms of Use');expect(legal).toContain('Acceptable Use Policy');expect(entry).toContain("p==='/terms-of-use'");expect(auth).toContain('confirm you are at least 18');});it('keeps unpublished investigation records out of public search',()=>{expect(read('src/searchRepository.ts')).toContain('i.published_at IS NOT NULL');});it('marks individual notifications read through an ownership-scoped lookup',()=>{const repo=read('src/dashboardRepository.ts'),routes=read('src/dashboardRoutes.ts');expect(repo).toContain('n.user_id=? AND n.id=?');expect(repo).toContain('markNotificationRead');expect(routes).toContain('openNotificationV3');});it('validates report targets and reconciles moderation state',()=>{expect(read('src/reportRoutes.ts')).toContain('You cannot report your own comment');expect(read('src/moderationRepository.ts')).toContain("status='RESOLVED'");expect(read('src/communityRepository.ts')).toContain('UPDATE moderation_queue SET status=?');});it('surfaces a bounded mixed public activity feed and groups discussion threads',()=>{const repo=read('src/investigationRepository.ts'),views=read('src/investigationViews.ts');expect(repo).toContain('recentActivity(limit=24)');expect(repo).toContain('COALESCE(root.created_at,c.created_at)');expect(views).toContain('Recent activity');expect(views).toContain('correction-');});});

describe('complete legal policy suite',()=>{it('publishes and routes every signup policy',()=>{const legal=read('src/legalRoutes.ts'),entry=read('src/entry.ts'),auth=read('src/authRoutes.ts');for(const name of ['Privacy Policy','Community Guidelines','Evidence & Source Policy','Copyright & Intellectual Property Policy','Corrections & Disputes Policy'])expect(legal).toContain(name);for(const route of ["p==='/privacy'","p==='/community-guidelines'","p==='/evidence-policy'","p==='/copyright'","p==='/corrections'"])expect(entry).toContain(route);for(const href of ['/terms','/terms-of-use','/privacy','/acceptable-use','/community-guidelines','/evidence-policy','/copyright','/corrections'])expect(auth).toContain(`href=\"${href}\"`);});it('does not publish lawyer-review warning language',()=>{const legal=read('src/legalRoutes.ts');expect(legal).not.toMatch(/qualified counsel|lawyer review|legal review/i);});it('states the adult-only account rule',()=>{expect(read('src/legalRoutes.ts')).toContain('restricted to adults age 18 or older');});});

describe('session intro',()=>{it('plays the supplied cinematic intro once per browser tab session without SPA state',()=>{const views=read('src/views.ts');expect(views).toContain("sessionStorage.getItem('intel:intro:played')");expect(views).toContain('src=\"/intel_intro_animation.mp4?v=4\"');expect(views).toContain("sessionStorage.setItem('intel:intro:played','1')");expect(views).toContain("video.addEventListener('ended',finish");expect(views).toContain("video.addEventListener('error',finish");});});

describe('intro delivery hardening',()=>{it('renders splash visible by default and hides only for an already-seen tab session',()=>{const views=read('src/views.ts');expect(views).toContain('.intro-screen{display:grid');expect(views).toContain('.intel-intro-seen .intro-screen{display:none}');expect(views).toContain("autoplay preload=\"auto\"");expect(views).not.toContain('class=\"intro-skip\"');expect(views).toContain("video.controls=false");expect(views).toContain("video.removeAttribute('controls')");expect(views).toContain("video.defaultMuted=true");});it('forces homepage HTML through a no-store response',()=>{const entry=read('src/entry.ts');expect(entry).toContain("pathname==='/'");expect(entry).toContain("no-store, no-cache, must-revalidate, max-age=0");expect(entry).toContain("X-Intel-Release','intro-daaa618");});it('runs the application worker before static assets',()=>{expect(read('wrangler.jsonc')).toContain('"run_worker_first": true');});});
