import {describe,it,expect} from 'vitest';import fs from 'node:fs';
const read=(p:string)=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
describe('INTEL social architecture contracts',()=>{
 const migration=read('migrations-turso/0012_social_messaging_privacy.sql'),notificationMigration=read('migrations-turso/0013_social_notification_preferences.sql'),client=read('public/social.js'),worker=read('public/sw.js'),push=read('src/push.ts'),account=read('src/account.ts'),auth=read('src/authRoutes.ts'),routes=read('src/socialRoutes.ts'),repo=read('src/socialRepository.ts'),auth=read('src/authRoutes.ts'),views=read('src/views.ts'),entry=read('src/entry.ts'),rate=read('src/rateLimit.ts'),account=read('src/account.ts');
 it('uses canonical mutual friendship and indexed bounded messaging',()=>{expect(migration).toContain('PRIMARY KEY(user_low_id,user_high_id)');expect(migration).toContain('idx_private_messages_conversation_time');expect(repo).toContain("status!=='FRIENDS'");expect(repo).toContain('LIMIT ?');});
 it('keeps private media in R2 behind conversation authorization',()=>{expect(routes).toContain('c.env.EVIDENCE.put');expect(routes).toContain('messageAttachment');expect(routes).toContain('repo(c).member(conversationId,c.user!.id)');});
 it('enforces private DOB and explicit signup choices',()=>{expect(auth).toContain('date_of_birth');expect(auth).toContain('You must be at least 18 years old');expect(auth).toContain("accept_policies!=='yes'");expect(auth).toContain("accept_notifications!=='yes'");expect(auth).toContain("accept_cookies!=='yes'");expect(migration).toContain('date_of_birth TEXT');});
 it('replaces Latest primary nav with Messages while preserving home sorting',()=>{expect(views).not.toContain('href="/latest" aria-label="Latest"');expect(views).toContain('href="/messages" aria-label="Messages"');});
 it('uses mobile viewport-stable chat and keyset cursors',()=>{expect(routes).toContain('chat-transcript');expect(routes).toContain('client_nonce');expect(repo).toContain('m.created_at<?');expect(views).toContain('--vvh');});
 it('hardens social abuse paths and blocking',()=>{expect(rate).toContain("friendSearch:{limit:24");expect(rate).toContain("friendRequest:{limit:12");expect(rate).toContain("message:{limit:90");expect(entry).toContain("checkRateLimit(request,'friendSearch')");expect(routes).toContain('blockFriend');expect(account).toContain('Blocked accounts');});
 it('surfaces bounded keyset pagination controls',()=>{expect(routes).toContain('Load older chats');expect(routes).toContain('Load older messages');expect(repo).toContain('m.created_at<?');expect(repo).toContain('c.updated_at<?');});
 it('keeps social notification preferences separate from investigation preferences',()=>{expect(notificationMigration).toContain('social_notification_preferences');expect(notificationMigration).not.toMatch(/CREATE TABLE notification_preferences\s*\(/);expect(repo).toContain('social_notification_preferences');});
 it('delivers push as failure-contained background work',()=>{expect(push).toContain('webpush.sendNotification');expect(push).toContain('Promise.allSettled');expect(push).toContain('executionCtx.waitUntil');expect(push).toContain("status===404||status===410");});
 it('renders and enforces private DOB collection',()=>{expect(auth).toContain('name="date_of_birth"');expect(auth).toContain('Your birthday is private and is not shown publicly');expect(auth).toContain("if(dobDate>cutoff)");expect(account).toContain('completeBirthday');expect(account).toContain('date_of_birth IS NULL');});
 it('provides an adjustable optimized avatar editor',()=>{expect(account).toContain('avatar-editor');expect(client).toContain('data-avatar-zoom');expect(client).toContain('createImageBitmap');expect(client).toContain("canvas.toBlob(r,'image/webp',.88)");});
 it('wires durable push subscription lifecycle',()=>{expect(repo).toContain('savePushDevice');expect(routes).toContain('savePushSubscription');expect(entry).toContain("p==='/api/push/subscriptions'");expect(client).toContain('PushManager');expect(worker).toContain("addEventListener('push'");});
 it('supports private friend sharing and progressive chat history',()=>{expect(routes).toContain('sharePicker');expect(routes).toContain('shareToFriend');expect(entry).toContain("p==='/share/friend'");expect(client).toContain("a.older-messages");expect(client).toContain('scrollHeight-beforeHeight');});
 it('centralizes profile activity privacy',()=>{expect(migration).toContain("profile_visibility TEXT NOT NULL DEFAULT 'PUBLIC'");expect(repo).toContain("u.profile_visibility==='FRIENDS'");expect(repo).toContain("u.profile_visibility==='PUBLIC'");});
});
